type StretchHubExerciseLike = {
  name?: string | null;
  slug?: string | null;
  primary_muscle?: string | null;
  equipment?: string | null;
  movement_pattern?: string | null;
};

export type StretchReferenceItem = {
  id: string;
  name: string;
  targetAreas: string[];
  bodyPosition: string;
  durationGuidance: string;
  equipment: string;
  bestFor: string[];
  coachingCue: string;
  howTo: string;
};

export const STRETCH_HUB_HERO_SRC = "/exercises/stretch-hub-hero.svg";
export const STRETCH_HUB_META_ITEMS = ["Mobility", "Recovery", "Bodyweight"] as const;
export const STRETCH_HUB_CHIP_LABELS = ["Mobility", "Recovery", "Bodyweight"] as const;
export const STRETCH_HUB_GUIDE_COPY = "Collection of stretches to use before training, after training, or any time you want a simple mobility guide for recovery and reset work.";

export const STRETCH_LIBRARY: StretchReferenceItem[] = [
  {
    id: "half-kneeling-hip-flexor-stretch",
    name: "Half-Kneeling Hip Flexor Stretch",
    targetAreas: ["Hip flexors", "Front thigh", "Anterior hip"],
    bodyPosition: "Half kneeling",
    durationGuidance: "20-40 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Lower-body warm-up", "Post-run reset"],
    coachingCue: "Keep the ribs stacked over the pelvis and squeeze the glute on the kneeling side.",
    howTo: "Set one knee down with the other foot flat in front. Tuck the pelvis slightly, stay tall through the torso, and glide the hips forward only until the front of the trailing hip opens up.",
  },
  {
    id: "thomas-hip-flexor-stretch",
    name: "Thomas Hip Flexor Stretch",
    targetAreas: ["Hip flexors", "Quads", "Anterior hip"],
    bodyPosition: "Supine",
    durationGuidance: "20-30 sec per side",
    equipment: "Bench or sturdy box",
    bestFor: ["Desk posture reset", "Front-hip mobility"],
    coachingCue: "Keep the low back quiet and let the hanging leg lengthen instead of forcing the knee down.",
    howTo: "Sit near the edge of a bench, hug one knee toward the chest, then roll back and let the opposite leg hang. Hold the tucked leg close while the hanging thigh relaxes to open the front of the hip.",
  },
  {
    id: "seated-hamstring-reach",
    name: "Seated Hamstring Reach",
    targetAreas: ["Hamstrings", "Calves", "Posterior chain"],
    bodyPosition: "Seated",
    durationGuidance: "20-45 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Lower-body cooldown", "Mobility reset"],
    coachingCue: "Reach from the hips first and keep the chest long instead of rounding hard through the low back.",
    howTo: "Sit tall with one leg extended and the other bent comfortably. Hinge forward over the straight leg until you feel tension along the back of the thigh, then breathe and hold without forcing the range.",
  },
  {
    id: "supine-hamstring-strap-stretch",
    name: "Supine Hamstring Strap Stretch",
    targetAreas: ["Hamstrings", "Calves", "Posterior chain"],
    bodyPosition: "Supine",
    durationGuidance: "20-40 sec per side",
    equipment: "Strap or towel",
    bestFor: ["Post-leg-day recovery", "Gentle flexibility work"],
    coachingCue: "Keep the opposite leg heavy on the floor and stop before the pelvis starts to tip.",
    howTo: "Lie on your back and loop a strap around one foot. Raise that leg toward the ceiling with a soft knee until you feel the back of the thigh lengthen, then hold steady while breathing normally.",
  },
  {
    id: "sprinter-hamstring-stretch",
    name: "Sprinter Hamstring Stretch",
    targetAreas: ["Hamstrings", "Calves", "Posterior chain"],
    bodyPosition: "Half kneeling",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Warm-up prep", "Running mobility"],
    coachingCue: "Hinge over the front leg with a long spine instead of collapsing into the low back.",
    howTo: "Start in a half-kneeling stance and gradually shift the hips back until the front leg straightens. Fold over the front thigh only to the point where the back of the leg begins to lengthen.",
  },
  {
    id: "doorway-pec-stretch",
    name: "Doorway Pec Stretch",
    targetAreas: ["Chest", "Front shoulder", "Biceps"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Doorway or upright post",
    bestFor: ["Upper-body recovery", "Desk posture reset"],
    coachingCue: "Let the chest open while keeping the shoulder blade gently set down and back.",
    howTo: "Place the forearm on a doorway with the elbow around shoulder height. Step through slowly until the chest opens, and stop before the shoulder rolls forward or pinches.",
  },
  {
    id: "wall-pec-minor-stretch",
    name: "Wall Pec Minor Stretch",
    targetAreas: ["Chest", "Front shoulder", "Pec minor"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Wall or upright post",
    bestFor: ["Desk posture reset", "Upper-body recovery"],
    coachingCue: "Open the chest without letting the shoulder dump forward into the joint.",
    howTo: "Place one forearm or hand on a wall slightly above shoulder height, then rotate the chest away from that arm. Hold where the upper chest and front shoulder begin to open.",
  },
  {
    id: "doorway-biceps-stretch",
    name: "Doorway Biceps Stretch",
    targetAreas: ["Biceps", "Chest", "Front shoulder"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Doorway or upright post",
    bestFor: ["Upper-body cooldown", "Pull-day recovery"],
    coachingCue: "Straighten the elbow and turn the chest gradually instead of jamming the shoulder back.",
    howTo: "Place the palm and arm against a doorway with the elbow nearly straight, then rotate the body away. Stop where the biceps and front of the shoulder begin to lengthen comfortably.",
  },
  {
    id: "cross-body-posterior-shoulder-stretch",
    name: "Cross-Body Posterior Shoulder Stretch",
    targetAreas: ["Rear shoulder", "Upper back", "Posterior shoulder"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Upper-body cooldown", "Throwing-sport recovery"],
    coachingCue: "Keep the shoulder down away from the ear while the arm moves across the body.",
    howTo: "Bring one arm straight across the chest and use the opposite hand to draw it in closer. Hold only until the back of the shoulder and upper back feel tension without twisting the torso.",
  },
  {
    id: "side-lying-shoulder-capsule-stretch",
    name: "Side-Lying Shoulder Capsule Stretch",
    targetAreas: ["Rear shoulder", "Rotator cuff", "Posterior shoulder"],
    bodyPosition: "Side lying",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Throwing-sport recovery", "Pressing recovery"],
    coachingCue: "Keep the shoulder packed and let the rotation come from the joint, not from rolling the chest back.",
    howTo: "Lie on one side with the lower arm out in front and the elbow bent to 90 degrees. Use the top hand to guide the forearm gently toward the floor until the back of the shoulder starts to open.",
  },
  {
    id: "overhead-triceps-stretch",
    name: "Overhead Triceps Stretch",
    targetAreas: ["Triceps", "Lats", "Shoulders"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Upper-body recovery", "Overhead mobility reset"],
    coachingCue: "Let the ribs stay stacked as the elbow points up instead of flaring wide behind you.",
    howTo: "Reach one arm overhead, bend the elbow, and place the hand behind the head or upper back. Use the opposite hand to guide the elbow gently upward until the back of the arm and side body open up.",
  },
  {
    id: "standing-side-bend-lat-stretch",
    name: "Standing Side-Bend Lat Stretch",
    targetAreas: ["Lats", "Obliques", "Side body"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Overhead training prep", "Full-body reset"],
    coachingCue: "Reach tall first, then arc sideways without collapsing through the chest.",
    howTo: "Stand tall with one arm overhead and the other relaxed at your side. Reach up, then bend gently away from the lifted arm until you feel the side of the torso lengthen.",
  },
  {
    id: "standing-lat-wall-stretch",
    name: "Standing Lat Wall Stretch",
    targetAreas: ["Lats", "Shoulders", "Side body"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Wall or upright post",
    bestFor: ["Overhead mobility", "Upper-body warm-up"],
    coachingCue: "Keep the hand anchored and sit the hips slightly back so the side body opens from wrist to pelvis.",
    howTo: "Place one hand on a wall or post at about shoulder height or slightly above it. Step back and sink the hips away from that hand until the lat and shoulder begin to lengthen.",
  },
  {
    id: "childs-pose-lat-reach",
    name: "Child's Pose Lat Reach",
    targetAreas: ["Lats", "Upper back", "Triceps"],
    bodyPosition: "Kneeling",
    durationGuidance: "30-45 sec",
    equipment: "Bodyweight",
    bestFor: ["Overhead training reset", "Breathing reset"],
    coachingCue: "Reach long through the hands and soften the ribs down as you exhale.",
    howTo: "Start on hands and knees, sit the hips back toward the heels, and walk the hands forward. Reach through the fingertips while keeping the neck relaxed and the breath steady.",
  },
  {
    id: "kneeling-bench-lat-stretch",
    name: "Kneeling Bench Lat Stretch",
    targetAreas: ["Lats", "Upper back", "Shoulders"],
    bodyPosition: "Kneeling",
    durationGuidance: "30-45 sec",
    equipment: "Bench",
    bestFor: ["Shoulder flexion mobility", "Upper-body cooldown"],
    coachingCue: "Keep the core lightly braced so the stretch lands in the lats instead of the low back.",
    howTo: "Kneel in front of a bench and place both hands on it with the elbows straight. Sink the hips back while keeping the arms long and the chest dropping between the shoulders.",
  },
  {
    id: "childs-pose-side-reach",
    name: "Child's Pose Side Reach",
    targetAreas: ["Lats", "Obliques", "Side body"],
    bodyPosition: "Kneeling",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Breathing reset", "Side-body mobility"],
    coachingCue: "Keep the hips anchored back as the hands walk off-center to lengthen one side at a time.",
    howTo: "Set up in child's pose, then walk both hands to one side while keeping the hips heavy toward the heels. Hold until the opposite side of the torso begins to open, then switch directions.",
  },
  {
    id: "figure-4-glute-stretch",
    name: "Figure-4 Glute Stretch",
    targetAreas: ["Glutes", "Piriformis", "Posterior hip"],
    bodyPosition: "Supine",
    durationGuidance: "20-40 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Post-leg-day recovery", "Hip rotation reset"],
    coachingCue: "Draw the legs in with the hands, not by yanking the neck or curling off the floor.",
    howTo: "Lie on your back, cross one ankle over the opposite thigh, and gently draw the support leg toward your chest. Hold the position where the back of the hip opens without twisting the pelvis.",
  },
  {
    id: "ninety-ninety-hip-stretch",
    name: "90/90 Hip Stretch",
    targetAreas: ["Glutes", "Hip rotators", "Posterior hip"],
    bodyPosition: "Seated",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Hip rotation mobility", "Warm-up prep"],
    coachingCue: "Stay tall through the torso and rotate from the hips before folding forward.",
    howTo: "Sit with one leg bent in front at roughly 90 degrees and the other bent behind you at 90 degrees. Hold tall or hinge over the front shin until the outside of the front hip begins to open.",
  },
  {
    id: "kneeling-groin-rockback",
    name: "Kneeling Groin Rockback",
    targetAreas: ["Adductors", "Groin", "Inner thigh"],
    bodyPosition: "Quadruped",
    durationGuidance: "6-8 slow reps per side",
    equipment: "Bodyweight",
    bestFor: ["Adductor mobility", "Warm-up prep"],
    coachingCue: "Keep the spine neutral and move the hips back under control instead of dropping into the stretch.",
    howTo: "Start on hands and knees, extend one leg out to the side with the foot flat, and rock the hips gently back toward the heel of the kneeling leg. Move in a slow rhythm until the inner thigh of the straight leg begins to lengthen.",
  },
  {
    id: "reclined-butterfly-stretch",
    name: "Reclined Butterfly Stretch",
    targetAreas: ["Adductors", "Groin", "Anterior hips"],
    bodyPosition: "Supine",
    durationGuidance: "20-30 sec",
    equipment: "Bodyweight",
    bestFor: ["Cooldown reset", "Gentle hip opening"],
    coachingCue: "Let the knees fall open under their own weight and keep the low back relaxed on the floor.",
    howTo: "Lie on your back, bring the soles of the feet together, and allow the knees to drift out to the sides. Support the legs if needed and breathe into the hips as they relax open.",
  },
  {
    id: "supine-spinal-twist",
    name: "Supine Spinal Twist",
    targetAreas: ["Mid-back", "Glutes", "Outer hip"],
    bodyPosition: "Supine",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Cooldown reset", "Rotational mobility"],
    coachingCue: "Keep the top shoulder heavy and let the breath ease the rotation deeper over time.",
    howTo: "Lie on your back, draw one knee across the body, and extend the opposite arm out to the side. Rotate only until you feel the hip and mid-back open while the shoulders stay relaxed.",
  },
  {
    id: "cat-cow-spinal-mobility",
    name: "Cat-Cow Spinal Mobility",
    targetAreas: ["Thoracic spine", "Low back", "Shoulders"],
    bodyPosition: "Quadruped",
    durationGuidance: "5-8 slow reps",
    equipment: "Bodyweight",
    bestFor: ["Warm-up prep", "Spinal mobility reset"],
    coachingCue: "Move one vertebra at a time and let the breath control the pace.",
    howTo: "Start on hands and knees, then alternate between rounding the spine up toward the ceiling and gently extending the chest forward. Move slowly enough to feel each segment of the spine change shape.",
  },
  {
    id: "knees-to-chest-stretch",
    name: "Knees-to-Chest Stretch",
    targetAreas: ["Low back", "Glutes", "Posterior chain"],
    bodyPosition: "Supine",
    durationGuidance: "20-30 sec",
    equipment: "Bodyweight",
    bestFor: ["Cooldown reset", "Low-back decompression"],
    coachingCue: "Pull just enough to feel the low back soften into the floor without rounding the neck.",
    howTo: "Lie on your back and draw one or both knees toward the chest. Hug the legs lightly while keeping the shoulders and jaw relaxed on the floor.",
  },
  {
    id: "seated-forward-fold",
    name: "Seated Forward Fold",
    targetAreas: ["Hamstrings", "Calves", "Low back"],
    bodyPosition: "Seated",
    durationGuidance: "20-30 sec",
    equipment: "Bodyweight",
    bestFor: ["Cooldown mobility", "Posterior-chain reset"],
    coachingCue: "Lengthen the spine first and fold from the hips rather than collapsing the chest straight down.",
    howTo: "Sit with both legs long in front of you and reach forward from the hips. Hold the position where the backs of the legs and lower spine feel a gentle, even stretch.",
  },
  {
    id: "sphinx-abdominal-stretch",
    name: "Sphinx Abdominal Stretch",
    targetAreas: ["Abdominals", "Hip flexors", "Front body"],
    bodyPosition: "Prone",
    durationGuidance: "15-25 sec",
    equipment: "Bodyweight",
    bestFor: ["Front-body opening", "Post-sitting reset"],
    coachingCue: "Press the forearms down and lengthen the chest forward instead of jamming into the low back.",
    howTo: "Lie face down and prop yourself up on the forearms with the elbows under the shoulders. Lift the chest gently until the abdominals and front of the hips begin to open.",
  },
  {
    id: "standing-calf-wall-stretch",
    name: "Standing Calf Wall Stretch",
    targetAreas: ["Calves", "Achilles", "Ankles"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Wall",
    bestFor: ["Run prep", "Lower-leg recovery"],
    coachingCue: "Keep the heel heavy and let the shin travel forward without collapsing the arch.",
    howTo: "Face a wall with one foot back and both feet pointed forward. Press the rear heel down and lean in until the calf lengthens, then slightly bend the back knee if you want to bias the lower calf.",
  },
  {
    id: "bent-knee-soleus-wall-stretch",
    name: "Bent-Knee Soleus Wall Stretch",
    targetAreas: ["Soleus", "Achilles", "Ankles"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Wall",
    bestFor: ["Ankle mobility", "Run and squat prep"],
    coachingCue: "Keep the heel planted as the back knee bends so the stretch shifts lower in the calf.",
    howTo: "Set up like a wall calf stretch, then bend the rear knee while keeping the heel on the floor. Hold where the lower calf and Achilles begin to lengthen without the foot rolling inward.",
  },
  {
    id: "kneeling-ankle-dorsiflexion-stretch",
    name: "Kneeling Ankle Dorsiflexion Stretch",
    targetAreas: ["Ankles", "Achilles", "Calves"],
    bodyPosition: "Half kneeling",
    durationGuidance: "8-10 slow reps per side",
    equipment: "Wall",
    bestFor: ["Squat prep", "Running mobility"],
    coachingCue: "Drive the knee forward over the toes while the heel stays heavy and the arch stays active.",
    howTo: "Set up in front of a wall with one foot forward and the heel down. Glide the front knee toward the wall and back out repeatedly, using a controlled range that opens the ankle without the heel lifting.",
  },
  {
    id: "standing-tibialis-anterior-stretch",
    name: "Standing Tibialis Anterior Stretch",
    targetAreas: ["Shins", "Ankles", "Top of foot"],
    bodyPosition: "Standing",
    durationGuidance: "15-25 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Lower-leg recovery", "Running cooldown"],
    coachingCue: "Keep the standing leg steady and go only far enough to feel the front of the shin and ankle open.",
    howTo: "Stand tall and place the top of one foot lightly on the floor behind you with the toes pointed. Gently lower weight into that foot until the front of the ankle and shin begin to lengthen.",
  },
  {
    id: "open-book-thoracic-rotation",
    name: "Open Book Thoracic Rotation",
    targetAreas: ["Mid-back", "Chest", "Shoulder girdle"],
    bodyPosition: "Side lying",
    durationGuidance: "5-8 slow reps per side",
    equipment: "Bodyweight",
    bestFor: ["Upper-body warm-up", "Rotation mobility"],
    coachingCue: "Rotate through the upper back and let the breath lead the motion instead of cranking the shoulder.",
    howTo: "Lie on your side with the knees stacked and arms straight out in front. Sweep the top arm open across the body, rotate the rib cage toward the floor behind you, then return with control.",
  },
  {
    id: "thread-the-needle-rotation",
    name: "Thread-the-Needle Rotation",
    targetAreas: ["Mid-back", "Rear shoulder", "Upper back"],
    bodyPosition: "Quadruped",
    durationGuidance: "5-8 slow reps per side",
    equipment: "Bodyweight",
    bestFor: ["Thoracic mobility", "Upper-body warm-up"],
    coachingCue: "Let the rib cage rotate while the support hand stays grounded and stable.",
    howTo: "Start on hands and knees, slide one arm under the body, and lower the shoulder toward the floor. Pause in the rotated position, then unwind and reach that same arm back up toward the ceiling.",
  },
  {
    id: "seated-thoracic-extension-chair",
    name: "Seated Thoracic Extension Stretch",
    targetAreas: ["Thoracic spine", "Chest", "Upper back"],
    bodyPosition: "Seated",
    durationGuidance: "5-8 slow reps",
    equipment: "Chair or bench",
    bestFor: ["Desk posture reset", "Upper-body warm-up"],
    coachingCue: "Lift through the sternum and extend over the upper back instead of hinging hard from the low back.",
    howTo: "Sit tall near the edge of a chair and place the hands behind the head. Gently extend the upper back over the chair or into open space while keeping the ribs controlled and the neck long.",
  },
  {
    id: "prone-cobra-chest-opener",
    name: "Prone Cobra Chest Opener",
    targetAreas: ["Chest", "Front shoulders", "Thoracic spine"],
    bodyPosition: "Prone",
    durationGuidance: "15-25 sec",
    equipment: "Bodyweight",
    bestFor: ["Posture reset", "Upper-body recovery"],
    coachingCue: "Lengthen through the crown of the head and lift from the upper back rather than jamming the low back.",
    howTo: "Lie face down with the arms by your sides, palms turned out. Gently lift the chest and hands off the floor while drawing the shoulder blades down and back, then hold the open position.",
  },
  {
    id: "couch-quad-stretch",
    name: "Couch Quad Stretch",
    targetAreas: ["Quads", "Hip flexors", "Front thigh"],
    bodyPosition: "Kneeling",
    durationGuidance: "20-30 sec per side",
    equipment: "Wall or bench",
    bestFor: ["Post-squat recovery", "Front-thigh mobility"],
    coachingCue: "Own the upright torso first, then chase more range only if the low back stays quiet.",
    howTo: "Set the back shin against a wall or bench with the front foot planted in front. Brace lightly, bring the torso tall, and hold where the quad and hip flexor stretch without dumping into the lumbar spine.",
  },
  {
    id: "standing-quadriceps-stretch",
    name: "Standing Quadriceps Stretch",
    targetAreas: ["Quads", "Hip flexors", "Front thigh"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Wall or support",
    bestFor: ["Pre-run mobility", "Lower-body cooldown"],
    coachingCue: "Keep the knees close and the pelvis neutral rather than arching the low back.",
    howTo: "Stand tall, hold a wall or support if needed, and pull one heel toward the glute with the hand on the same side. Hold where the front of the thigh lengthens while the standing leg stays steady.",
  },
  {
    id: "prone-quad-stretch",
    name: "Prone Quad Stretch",
    targetAreas: ["Quads", "Front thigh", "Hip flexors"],
    bodyPosition: "Prone",
    durationGuidance: "20-30 sec per side",
    equipment: "Strap or towel",
    bestFor: ["Post-leg-day recovery", "Gentle front-thigh mobility"],
    coachingCue: "Keep both hips grounded so the stretch stays in the thigh instead of twisting through the pelvis.",
    howTo: "Lie face down, loop a strap around one foot, and draw the heel toward the glute. Hold only to the point where the front of the thigh opens while the pelvis stays heavy on the floor.",
  },
  {
    id: "static-standing-adductor-stretch",
    name: "Static Standing Adductor Stretch",
    targetAreas: ["Adductors", "Groin", "Inner thigh"],
    bodyPosition: "Standing",
    durationGuidance: "15-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Lateral movement prep", "Hip mobility"],
    coachingCue: "Shift the hips back into the loaded side and keep the long leg straight without collapsing the torso.",
    howTo: "Take a wide stance and shift your body weight into one hip while the opposite leg stays extended. Hold where the inner thigh of the straight leg begins to lengthen, then repeat on the other side.",
  },
  {
    id: "frog-adductor-stretch",
    name: "Frog Adductor Stretch",
    targetAreas: ["Adductors", "Groin", "Inner thighs"],
    bodyPosition: "Quadruped",
    durationGuidance: "20-30 sec",
    equipment: "Bodyweight",
    bestFor: ["Hip opening", "Adductor mobility"],
    coachingCue: "Keep the spine long and ease the hips back only as far as the groin can relax without pinching.",
    howTo: "Start on hands and knees, widen the knees, and bring the shins out to the sides. Slowly shift the hips back until the inner thighs begin to open, then hold the position with steady breathing.",
  },
  {
    id: "butterfly-groin-stretch",
    name: "Butterfly Groin Stretch",
    targetAreas: ["Adductors", "Groin", "Inner thigh"],
    bodyPosition: "Seated",
    durationGuidance: "20-30 sec",
    equipment: "Bodyweight",
    bestFor: ["Hip opening", "Cooldown mobility"],
    coachingCue: "Sit tall before leaning forward and let the knees relax toward the floor instead of forcing them.",
    howTo: "Sit upright with the soles of the feet together and the knees dropped out to the sides. Hold the feet or ankles and hinge forward slightly until the inner thighs open up.",
  },
  {
    id: "worlds-greatest-stretch",
    name: "World's Greatest Stretch",
    targetAreas: ["Hip flexors", "Hamstrings", "Thoracic spine"],
    bodyPosition: "Split stance",
    durationGuidance: "4-6 slow reps per side",
    equipment: "Bodyweight",
    bestFor: ["Dynamic warm-up", "Full-body mobility"],
    coachingCue: "Own the long exhale at each position and move segment by segment instead of rushing through it.",
    howTo: "Step into a long lunge, place the hands near the front foot, and alternate between opening the chest toward the lead leg and lengthening the front hamstring. Flow slowly through each phase before switching sides.",
  },
  {
    id: "low-lunge-reach-and-rotate",
    name: "Low Lunge Reach and Rotate",
    targetAreas: ["Hip flexors", "Thoracic spine", "Side body"],
    bodyPosition: "Half kneeling",
    durationGuidance: "4-6 slow reps per side",
    equipment: "Bodyweight",
    bestFor: ["Dynamic warm-up", "Full-body mobility"],
    coachingCue: "Stay tall through the kneeling hip as the upper back rotates and the reach follows the breath.",
    howTo: "Set up in a low lunge, then reach the inside arm up and across into a gentle rotation. Alternate between the open reach and the starting position with slow, deliberate reps.",
  },
  {
    id: "wall-shoulder-flexion-stretch",
    name: "Wall Shoulder Flexion Stretch",
    targetAreas: ["Shoulders", "Lats", "Triceps"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Wall",
    bestFor: ["Overhead mobility", "Pressing warm-up"],
    coachingCue: "Keep the ribs down as the arm reaches up so the stretch stays in the shoulder and side body.",
    howTo: "Face a wall, place one hand on it overhead, and step the body slightly back. Sink the chest down and forward until the shoulder and side body open without the low back taking over.",
  },
  {
    id: "wrist-flexor-wall-stretch",
    name: "Wrist Flexor Wall Stretch",
    targetAreas: ["Forearm flexors", "Wrists", "Palms"],
    bodyPosition: "Standing",
    durationGuidance: "15-25 sec per side",
    equipment: "Wall",
    bestFor: ["Grip recovery", "Upper-body cooldown"],
    coachingCue: "Straighten the elbow and open the palm without forcing the wrist into pain.",
    howTo: "Place the palm on a wall with the fingers pointing down or back and the elbow straight. Shift the body gently away until the inside of the forearm begins to lengthen.",
  },
  {
    id: "kneeling-toe-flexor-stretch",
    name: "Kneeling Toe Flexor Stretch",
    targetAreas: ["Toes", "Plantar fascia", "Arches"],
    bodyPosition: "Kneeling",
    durationGuidance: "15-25 sec",
    equipment: "Bodyweight",
    bestFor: ["Foot mobility", "Running recovery"],
    coachingCue: "Ease into the toes gradually and keep the ankles aligned rather than rolling outward.",
    howTo: "Kneel with the toes tucked under and sit back lightly toward the heels. Hold where the bottoms of the feet and toes begin to stretch without sharp pressure.",
  },
  {
    id: "standing-plantar-fascia-stretch",
    name: "Standing Plantar Fascia Stretch",
    targetAreas: ["Plantar fascia", "Arches", "Toes"],
    bodyPosition: "Standing",
    durationGuidance: "15-25 sec per side",
    equipment: "Wall or step",
    bestFor: ["Foot recovery", "Morning mobility"],
    coachingCue: "Keep the heel grounded and let the big toe extend so the arch opens along its full length.",
    howTo: "Place the toes of one foot up against a wall, box, or step with the heel on the floor. Gently move the shin forward until the arch and underside of the foot begin to lengthen.",
  },
  {
    id: "wrist-extensor-wall-stretch",
    name: "Wrist Extensor Wall Stretch",
    targetAreas: ["Forearm extensors", "Wrists", "Top of forearm"],
    bodyPosition: "Standing",
    durationGuidance: "15-25 sec per side",
    equipment: "Wall",
    bestFor: ["Typing reset", "Grip-heavy training recovery"],
    coachingCue: "Keep the shoulder relaxed and let the sensation stay in the top of the forearm.",
    howTo: "Extend one arm in front of you and gently flex the wrist with the opposite hand or against a wall. Hold where the back of the forearm opens up without sharp wrist discomfort.",
  },
  {
    id: "prayer-wrist-stretch",
    name: "Prayer Wrist Stretch",
    targetAreas: ["Wrists", "Forearm flexors", "Palms"],
    bodyPosition: "Standing",
    durationGuidance: "15-25 sec",
    equipment: "Bodyweight",
    bestFor: ["Typing reset", "Grip recovery"],
    coachingCue: "Keep the palms pressed together while the elbows stay relaxed and the shoulders stay down.",
    howTo: "Place the palms together in front of the chest, then lower the hands toward the waist while keeping the palms connected. Stop when the wrists and forearms begin to lengthen evenly.",
  },
  {
    id: "seated-upper-trap-stretch",
    name: "Seated Upper Trap Stretch",
    targetAreas: ["Upper traps", "Neck", "Shoulders"],
    bodyPosition: "Seated",
    durationGuidance: "15-25 sec per side",
    equipment: "Chair",
    bestFor: ["Desk reset", "Neck tension relief"],
    coachingCue: "Let the opposite shoulder stay heavy as the head tilts away.",
    howTo: "Sit tall and gently tilt one ear toward the shoulder. Use the hand on the same side for a light assist only if you need a little more stretch through the top of the neck and shoulder.",
  },
  {
    id: "levator-scapulae-stretch",
    name: "Levator Scapulae Stretch",
    targetAreas: ["Neck", "Upper traps", "Rear shoulder"],
    bodyPosition: "Seated",
    durationGuidance: "15-25 sec per side",
    equipment: "Chair",
    bestFor: ["Desk posture reset", "Overhead training recovery"],
    coachingCue: "Turn the nose toward the armpit and keep the chest lifted while the shoulder stays down.",
    howTo: "Sit tall, rotate the head about 45 degrees, then nod the chin down toward the armpit. Use a gentle hand assist if needed until the back and side of the neck begin to soften.",
  },
  {
    id: "seated-neck-rotation-stretch",
    name: "Seated Neck Rotation Stretch",
    targetAreas: ["Neck", "Scalenes", "Upper traps"],
    bodyPosition: "Seated",
    durationGuidance: "15-20 sec per side",
    equipment: "Chair",
    bestFor: ["Desk reset", "Driving stiffness relief"],
    coachingCue: "Rotate only to mild tension and keep the chin level rather than tipping it up.",
    howTo: "Sit tall and slowly turn the head to one side as if looking over the shoulder. Hold where the front and side of the neck feel a gentle stretch, then repeat to the other side.",
  },
  {
    id: "standing-tfl-crossover-stretch",
    name: "Standing TFL Crossover Stretch",
    targetAreas: ["Tensor fasciae latae", "Lateral hip", "Outer thigh"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Wall or support",
    bestFor: ["Running recovery", "Lateral hip mobility"],
    coachingCue: "Cross the leg behind you and lean from the hip rather than twisting the knee inward.",
    howTo: "Stand tall near a wall, cross one leg behind the other, and shift the hips gently toward the front leg. Add a small side reach until the outer hip and upper thigh begin to lengthen.",
  },
  {
    id: "seated-piriformis-stretch",
    name: "Seated Piriformis Stretch",
    targetAreas: ["Piriformis", "Glutes", "Posterior hip"],
    bodyPosition: "Seated",
    durationGuidance: "20-30 sec per side",
    equipment: "Chair or bench",
    bestFor: ["Desk reset", "Hip rotation mobility"],
    coachingCue: "Sit tall before hinging forward so the stretch lands in the back of the hip instead of the spine.",
    howTo: "Sit on a chair and cross one ankle over the opposite knee. Keep the chest long and hinge forward until the crossed-side glute and deep hip begin to open.",
  },
  {
    id: "single-knee-to-chest-stretch",
    name: "Single Knee-to-Chest Stretch",
    targetAreas: ["Glutes", "Low back", "Posterior hip"],
    bodyPosition: "Supine",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Cooldown reset", "Gentle low-back relief"],
    coachingCue: "Keep the opposite leg long and heavy while the knee draws in without cranking through the neck.",
    howTo: "Lie on your back with one leg extended and pull the opposite knee toward the chest. Hold only until the back of the hip and low back begin to soften.",
  },
  {
    id: "happy-baby-hip-stretch",
    name: "Happy Baby Hip Stretch",
    targetAreas: ["Adductors", "Glutes", "Posterior hip"],
    bodyPosition: "Supine",
    durationGuidance: "20-30 sec",
    equipment: "Bodyweight",
    bestFor: ["Hip opening", "Recovery reset"],
    coachingCue: "Keep the tailbone heavy and let the knees drift wide instead of yanking the feet down.",
    howTo: "Lie on your back, draw the knees toward the torso, and hold the outsides of the feet or shins. Let the knees open out toward the armpits while the low back stays relaxed on the floor.",
  },
  {
    id: "wide-leg-seated-forward-fold",
    name: "Wide-Leg Seated Forward Fold",
    targetAreas: ["Hamstrings", "Adductors", "Posterior chain"],
    bodyPosition: "Seated",
    durationGuidance: "20-40 sec",
    equipment: "Bodyweight",
    bestFor: ["Lower-body cooldown", "Straddle mobility"],
    coachingCue: "Lead with a long chest and hinge from the hips before the spine starts to round.",
    howTo: "Sit with the legs spread into a comfortable wide stance. Hinge forward between the legs only until the hamstrings and inner thighs begin to lengthen evenly.",
  },
  {
    id: "cossack-adductor-rock",
    name: "Cossack Adductor Rock",
    targetAreas: ["Adductors", "Groin", "Ankles"],
    bodyPosition: "Standing",
    durationGuidance: "5-6 slow reps per side",
    equipment: "Bodyweight",
    bestFor: ["Dynamic warm-up", "Lateral movement prep"],
    coachingCue: "Stay tall through the chest and move side to side with control instead of dropping into the bottom position.",
    howTo: "Take a wide stance and shift your weight toward one hip while the opposite leg stays long. Alternate sides slowly, letting the groin and ankle open as each hip takes load.",
  },
  {
    id: "quadratus-lumborum-doorway-stretch",
    name: "Quadratus Lumborum Doorway Stretch",
    targetAreas: ["Quadratus lumborum", "Side body", "Obliques"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Doorframe or upright post",
    bestFor: ["Side-body reset", "Post-lifting recovery"],
    coachingCue: "Reach long before you lean so the side body opens from ribs to pelvis.",
    howTo: "Hold a doorway or upright with one hand overhead, then step the hips slightly away from that arm. Lean gently until the side of the torso and low-rib area begin to lengthen.",
  },
  {
    id: "bear-hug-rhomboid-stretch",
    name: "Bear-Hug Rhomboid Stretch",
    targetAreas: ["Rhomboids", "Upper back", "Rear shoulders"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec",
    equipment: "Bodyweight",
    bestFor: ["Upper-back reset", "Posture recovery"],
    coachingCue: "Reach the elbows forward and slightly up while letting the shoulder blades glide apart.",
    howTo: "Wrap the arms around yourself as if giving a big hug, stacking one elbow over the other. Reach forward through the elbows until the space between the shoulder blades begins to open.",
  },
  {
    id: "wall-serratus-reach-stretch",
    name: "Wall Serratus Reach Stretch",
    targetAreas: ["Serratus anterior", "Lats", "Upper ribs"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Wall",
    bestFor: ["Overhead prep", "Upper-body mobility"],
    coachingCue: "Reach around the ribcage and let the shoulder blade glide forward instead of shrugging upward.",
    howTo: "Place one forearm or palm on a wall and reach forward as if sliding the shoulder blade around the ribs. Step the body slightly away until the side chest and upper ribcage begin to open.",
  },
  {
    id: "lateral-calf-peroneal-stretch",
    name: "Lateral Calf Peroneal Stretch",
    targetAreas: ["Peroneals", "Outer calf", "Ankles"],
    bodyPosition: "Standing",
    durationGuidance: "15-25 sec per side",
    equipment: "Wall or support",
    bestFor: ["Ankle mobility", "Running recovery"],
    coachingCue: "Keep the heel grounded and roll pressure slightly toward the outer edge only until the lateral calf begins to lengthen.",
    howTo: "Stand facing a wall and stagger the feet. Press the back heel down, then gently shift pressure toward the outside of that foot until the outer calf and ankle begin to stretch.",
  },
  {
    id: "standing-side-body-doorframe-stretch",
    name: "Standing Side-Body Doorframe Stretch",
    targetAreas: ["Side body", "Lats", "Obliques"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Doorframe or upright post",
    bestFor: ["Breathing reset", "Full-body mobility"],
    coachingCue: "Reach high and let the ribs expand on the open side without arching through the low back.",
    howTo: "Grip a doorway with one hand overhead and step the same-side foot slightly behind you. Lean the hips away from the arm until the side body opens from the wrist down through the ribs.",
  },
  {
    id: "supine-crossover-lateral-hip-stretch",
    name: "Supine Crossover Lateral Hip Stretch",
    targetAreas: ["Outer hip", "Glute medius", "Lateral hip"],
    bodyPosition: "Supine",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Hip reset", "Lower-body recovery"],
    coachingCue: "Keep both shoulders quiet and move only until the outer hip starts to open.",
    howTo: "Lie on your back, bend one knee, and guide that leg gently across the body while the pelvis stays mostly level. Hold where the outer hip and side glute begin to lengthen.",
  },
  {
    id: "puppy-pose-shoulder-stretch",
    name: "Puppy Pose Shoulder Stretch",
    targetAreas: ["Shoulders", "Lats", "Upper back"],
    bodyPosition: "Kneeling",
    durationGuidance: "20-30 sec",
    equipment: "Bodyweight",
    bestFor: ["Overhead mobility", "Upper-body cooldown"],
    coachingCue: "Keep the hips stacked over the knees and let the chest melt down without dumping into the low back.",
    howTo: "Start on hands and knees, walk the hands forward, and lower the chest toward the floor while the hips stay above the knees. Hold where the shoulders and side body begin to open comfortably.",
  },
  {
    id: "thread-the-needle-shoulder-stretch",
    name: "Thread-the-Needle Shoulder Stretch",
    targetAreas: ["Rear shoulder", "Thoracic spine", "Upper back"],
    bodyPosition: "Quadruped",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Upper-back mobility", "Pressing recovery"],
    coachingCue: "Reach long through the threading arm and let the rotation come from the upper back rather than cranking the neck.",
    howTo: "Start on hands and knees, slide one arm under the torso, and lower that shoulder and the side of the head toward the floor. Hold where the back of the shoulder and upper spine begin to open, then switch sides.",
  },
  {
    id: "kneeling-triceps-bench-stretch",
    name: "Kneeling Triceps Bench Stretch",
    targetAreas: ["Triceps", "Lats", "Shoulders"],
    bodyPosition: "Kneeling",
    durationGuidance: "20-30 sec",
    equipment: "Bench or box",
    bestFor: ["Overhead mobility", "Upper-body cooldown"],
    coachingCue: "Let the elbows stay narrow and brace the ribs lightly so the stretch lands through the arms and side body.",
    howTo: "Kneel in front of a bench, place the elbows on it, and bend the arms so the hands move behind the head. Sink the chest gently down until the triceps and lats begin to lengthen.",
  },
  {
    id: "wall-external-rotation-shoulder-stretch",
    name: "Wall External Rotation Shoulder Stretch",
    targetAreas: ["Rotator cuff", "Front shoulder", "Chest"],
    bodyPosition: "Standing",
    durationGuidance: "15-25 sec per side",
    equipment: "Wall",
    bestFor: ["Shoulder prep", "Pressing mobility"],
    coachingCue: "Keep the elbow pinned at shoulder height and rotate only until the front shoulder opens without pinching.",
    howTo: "Stand next to a wall with the elbow bent to 90 degrees and the upper arm near shoulder height. Set the forearm against the wall and gently turn the chest away until the front of the shoulder and chest begin to open.",
  },
  {
    id: "strap-shoulder-extension-stretch",
    name: "Strap Shoulder Extension Stretch",
    targetAreas: ["Front shoulders", "Biceps", "Chest"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec",
    equipment: "Strap or towel",
    bestFor: ["Desk posture reset", "Upper-body recovery"],
    coachingCue: "Lift the sternum softly and move the arms back only until the front shoulders open without flaring the ribs.",
    howTo: "Hold a strap behind the hips with a wide grip and gently draw the arms back and slightly away from the body. Pause where the chest and front shoulders begin to lengthen evenly.",
  },
  {
    id: "seated-straddle-side-reach",
    name: "Seated Straddle Side Reach",
    targetAreas: ["Adductors", "Side body", "Hamstrings"],
    bodyPosition: "Seated",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Straddle mobility", "Cooldown reset"],
    coachingCue: "Stay tall through the spine and reach over the leg instead of collapsing forward.",
    howTo: "Sit in a comfortable straddle, place one hand on the floor or leg, and reach the opposite arm overhead. Lean gently toward one side until the inner thigh and side body begin to open, then switch sides.",
  },
  {
    id: "half-kneeling-hip-internal-rotation-stretch",
    name: "Half-Kneeling Hip Internal Rotation Stretch",
    targetAreas: ["Hip internal rotators", "Glutes", "Posterior hip"],
    bodyPosition: "Half kneeling",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Hip rotation mobility", "Warm-up prep"],
    coachingCue: "Keep the pelvis square and move slowly until the deep hip begins to open without torque through the knee.",
    howTo: "Set up in a half-kneeling stance and gently move the front knee inward while the foot stays planted. Hold where the deep hip and back of the glute begin to feel tension.",
  },
  {
    id: "ninety-ninety-switch-flow",
    name: "90/90 Switch Flow",
    targetAreas: ["Hip rotators", "Glutes", "Anterior hip"],
    bodyPosition: "Seated",
    durationGuidance: "4-6 slow reps per side",
    equipment: "Bodyweight",
    bestFor: ["Dynamic warm-up", "Hip mobility"],
    coachingCue: "Rotate both legs under control and stay tall instead of rocking backward to escape the range.",
    howTo: "Sit with both knees bent and rotate the legs from one 90/90 position to the other in a smooth side-to-side flow. Pause briefly in each end range before switching directions.",
  },
  {
    id: "kneeling-shin-top-foot-stretch",
    name: "Kneeling Shin and Top-of-Foot Stretch",
    targetAreas: ["Shins", "Top of foot", "Ankles"],
    bodyPosition: "Kneeling",
    durationGuidance: "15-25 sec",
    equipment: "Bodyweight",
    bestFor: ["Foot mobility", "Ankle reset"],
    coachingCue: "Sit back gradually and keep the ankles aligned so the stretch stays smooth across the front of the foot.",
    howTo: "Kneel with the tops of the feet flat on the floor and sit the hips lightly toward the heels. Hold where the shins and top of the feet begin to lengthen without sharp pressure.",
  },
  {
    id: "seated-toe-extension-stretch",
    name: "Seated Toe Extension Stretch",
    targetAreas: ["Toes", "Plantar fascia", "Forefoot"],
    bodyPosition: "Seated",
    durationGuidance: "15-20 sec per side",
    equipment: "Chair or bench",
    bestFor: ["Foot recovery", "Walking comfort reset"],
    coachingCue: "Pull the toes back evenly and stop before the arch starts to cramp.",
    howTo: "Sit comfortably, cross one ankle over the opposite knee, and gently draw the toes back with the hand on the same side. Hold where the underside of the toes and forefoot begin to lengthen.",
  },
  {
    id: "sternocleidomastoid-stretch",
    name: "Sternocleidomastoid Stretch",
    targetAreas: ["Neck", "Scalenes", "Front of neck"],
    bodyPosition: "Seated",
    durationGuidance: "15-20 sec per side",
    equipment: "Chair",
    bestFor: ["Desk reset", "Neck tension relief"],
    coachingCue: "Lift the chest gently and rotate only until the front side of the neck begins to open.",
    howTo: "Sit tall, tip one ear slightly back, and rotate the face away from the stretching side. Hold where the front and side of the neck begin to lengthen without forcing the head back.",
  },
  {
    id: "forearm-pronation-stretch",
    name: "Forearm Pronation Stretch",
    targetAreas: ["Forearm pronators", "Wrists", "Elbows"],
    bodyPosition: "Standing",
    durationGuidance: "15-20 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Grip recovery", "Elbow comfort reset"],
    coachingCue: "Keep the elbow near the side and rotate gently until the forearm begins to tension evenly.",
    howTo: "Bend one elbow to 90 degrees at your side and use the opposite hand to rotate the forearm inward. Hold at mild tension along the forearm without forcing the wrist.",
  },
  {
    id: "forearm-supination-stretch",
    name: "Forearm Supination Stretch",
    targetAreas: ["Forearm supinators", "Wrists", "Elbows"],
    bodyPosition: "Standing",
    durationGuidance: "15-20 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Grip recovery", "Elbow comfort reset"],
    coachingCue: "Rotate through a smooth range and keep the shoulder relaxed so the sensation stays in the forearm.",
    howTo: "Bend one elbow to 90 degrees at your side and use the opposite hand to rotate the forearm outward. Stop where the forearm and elbow line begin to feel a gentle stretch.",
  },
  {
    id: "standing-it-band-side-reach",
    name: "Standing IT Band Side Reach",
    targetAreas: ["Outer thigh", "Lateral hip", "Side body"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Wall or support",
    bestFor: ["Lateral line mobility", "Run and squat recovery"],
    coachingCue: "Cross the outside leg behind and reach up before leaning, so the whole lateral chain lengthens together.",
    howTo: "Stand tall, cross one leg behind the other, and reach the same-side arm overhead. Lean away from the back leg until the outer hip, thigh, and side body begin to open.",
  },
  {
    id: "wall-angel-shoulder-mobility",
    name: "Wall Angel Shoulder Mobility",
    targetAreas: ["Chest", "Shoulders", "Upper back"],
    bodyPosition: "Standing",
    durationGuidance: "6-8 slow reps",
    equipment: "Wall",
    bestFor: ["Posture reset", "Upper-body warm-up"],
    coachingCue: "Keep the ribs quiet and slide only through the range where the shoulders stay smooth against the wall.",
    howTo: "Stand with the back against a wall and bring the arms up into a bent goalpost position. Slide the arms upward and back down slowly while keeping the torso stacked and the shoulders open.",
  },
  {
    id: "side-lying-windmill-stretch",
    name: "Side-Lying Windmill Stretch",
    targetAreas: ["Thoracic spine", "Chest", "Front shoulder"],
    bodyPosition: "Side lying",
    durationGuidance: "4-6 slow reps per side",
    equipment: "Bodyweight",
    bestFor: ["Thoracic mobility", "Warm-up prep"],
    coachingCue: "Let the top arm draw a wide arc and keep the knees stacked so the motion stays in the upper back.",
    howTo: "Lie on one side with the hips and knees bent, reach both arms forward, then sweep the top arm up and around toward the floor behind you. Move slowly and follow the hand with the eyes as the chest opens.",
  },
  {
    id: "deep-squat-pry-hold",
    name: "Deep Squat Pry Hold",
    targetAreas: ["Ankles", "Adductors", "Hips"],
    bodyPosition: "Squat",
    durationGuidance: "20-30 sec",
    equipment: "Bodyweight or support",
    bestFor: ["Lower-body mobility", "Pre-lift prep"],
    coachingCue: "Stay tall through the chest and gently pry the knees apart without letting the heels peel up.",
    howTo: "Drop into a comfortable deep squat and hold a support if needed. Use the elbows or hands to guide the knees outward lightly while the hips and ankles settle into the position.",
  },
  {
    id: "half-kneeling-adductor-glide",
    name: "Half-Kneeling Adductor Glide",
    targetAreas: ["Adductors", "Groin", "Inner thigh"],
    bodyPosition: "Half kneeling",
    durationGuidance: "5-6 slow reps per side",
    equipment: "Bodyweight",
    bestFor: ["Dynamic warm-up", "Groin prep"],
    coachingCue: "Keep the torso long and glide in and out instead of bouncing into the inner thigh.",
    howTo: "Start in a half-kneeling stance with the front foot wider than usual and gently shift the hips back and in. Move through a slow, repeatable range until the inner thigh begins to open.",
  },
  {
    id: "rear-delt-doorway-stretch",
    name: "Rear Delt Doorway Stretch",
    targetAreas: ["Rear shoulder", "Upper back", "Posterior shoulder"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Doorway or upright post",
    bestFor: ["Upper-body recovery", "Post-pull-day reset"],
    coachingCue: "Keep the shoulder low and rotate the torso only until the back of the shoulder begins to open.",
    howTo: "Stand beside a doorway, place one arm across the body against the frame, and turn the chest away slightly. Hold where the rear shoulder and upper back start to lengthen.",
  },
  {
    id: "reverse-prayer-forearm-stretch",
    name: "Reverse Prayer Forearm Stretch",
    targetAreas: ["Wrists", "Forearm extensors", "Forearms"],
    bodyPosition: "Standing",
    durationGuidance: "15-20 sec",
    equipment: "Bodyweight",
    bestFor: ["Desk reset", "Grip recovery"],
    coachingCue: "Bring the backs of the hands together gently and keep the elbows relaxed so the stretch stays even through both forearms.",
    howTo: "Bring the backs of the hands together in front of the chest with the fingers pointing down. Lift or lower the hands slightly until the wrists and top of the forearms begin to lengthen.",
  },
  {
    id: "seated-calf-strap-stretch",
    name: "Seated Calf Strap Stretch",
    targetAreas: ["Calves", "Achilles", "Hamstrings"],
    bodyPosition: "Seated",
    durationGuidance: "20-30 sec per side",
    equipment: "Strap or towel",
    bestFor: ["Run recovery", "Lower-leg flexibility"],
    coachingCue: "Keep the knee long and draw the toes back only until the calf begins to tension cleanly.",
    howTo: "Sit with one leg extended and loop a strap around the ball of the foot. Pull the foot back gently toward you until the calf and back of the lower leg begin to lengthen.",
  },
  {
    id: "ankle-inversion-eversion-mobility",
    name: "Ankle Inversion and Eversion Mobility",
    targetAreas: ["Ankles", "Peroneals", "Inner ankle"],
    bodyPosition: "Seated",
    durationGuidance: "6-8 slow reps per side",
    equipment: "Chair or bench",
    bestFor: ["Ankle control", "Foot mobility"],
    coachingCue: "Move the ankle through its side-to-side range without twisting the knee or cramping the toes.",
    howTo: "Sit with one foot off the floor and slowly roll the sole inward and outward through a controlled range. Pause briefly at each edge of the movement before returning to center.",
  },
  {
    id: "side-lying-banana-stretch",
    name: "Side-Lying Banana Stretch",
    targetAreas: ["Side body", "Lats", "Outer hip"],
    bodyPosition: "Supine",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Breathing reset", "Full-body recovery"],
    coachingCue: "Reach long through both the hands and feet so the body forms one gentle curve instead of a hard crunch at the waist.",
    howTo: "Lie on your back and walk both feet and both hands slightly to one side so the body forms a crescent shape. Hold while breathing into the open side of the torso, then repeat the other way.",
  },
  {
    id: "scorpion-thoracic-rotation",
    name: "Scorpion Thoracic Rotation",
    targetAreas: ["Thoracic spine", "Hip flexors", "Front body"],
    bodyPosition: "Prone",
    durationGuidance: "4-6 slow reps per side",
    equipment: "Bodyweight",
    bestFor: ["Dynamic warm-up", "Rotational mobility"],
    coachingCue: "Move slowly and let the chest open from the upper back instead of forcing the low back to twist.",
    howTo: "Lie face down with the arms out wide, then reach one foot across the body toward the opposite side. Return with control and alternate sides through a smooth, open rotation.",
  },
  {
    id: "foam-roll-chest-opener-stretch",
    name: "Foam Roll Chest Opener Stretch",
    targetAreas: ["Chest", "Front shoulders", "Thoracic spine"],
    bodyPosition: "Supine",
    durationGuidance: "20-40 sec",
    equipment: "Foam roller",
    bestFor: ["Upper-body recovery", "Posture reset"],
    coachingCue: "Relax the ribs and let the arms fall open naturally instead of forcing the shoulders flat.",
    howTo: "Lie lengthwise on a foam roller so the head and spine are supported, then open the arms out to the sides. Hold where the chest and front shoulders begin to relax and lengthen.",
  },
  {
    id: "groiner-lunge-stretch",
    name: "Groiner Lunge Stretch",
    targetAreas: ["Adductors", "Hip flexors", "Hamstrings"],
    bodyPosition: "Split stance",
    durationGuidance: "4-6 slow reps per side",
    equipment: "Bodyweight",
    bestFor: ["Dynamic warm-up", "Lower-body prep"],
    coachingCue: "Sink the hips gradually and keep the front foot rooted as the groin and back hip open together.",
    howTo: "Step into a long lunge and bring both hands inside the front foot. Lower into the position, then rock slightly or hold while the inner thigh and opposite hip flexor begin to open.",
  },
  {
    id: "sleeper-shoulder-stretch",
    name: "Sleeper Shoulder Stretch",
    targetAreas: ["Rear shoulder", "Rotator cuff", "Posterior shoulder"],
    bodyPosition: "Side lying",
    durationGuidance: "15-25 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Throwing recovery", "Shoulder internal-rotation mobility"],
    coachingCue: "Keep the shoulder stacked and rotate only until the back of the joint opens without pinching in front.",
    howTo: "Lie on one side with the bottom shoulder and elbow bent to 90 degrees. Use the top hand to guide the lower forearm toward the floor until the back of the shoulder begins to stretch.",
  },
  {
    id: "heel-on-box-hamstring-stretch",
    name: "Heel-on-Box Hamstring Stretch",
    targetAreas: ["Hamstrings", "Calves", "Posterior chain"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Box or bench",
    bestFor: ["Lower-body cooldown", "Run and hinge recovery"],
    coachingCue: "Keep the spine long and hinge from the hips instead of rounding down toward the shin.",
    howTo: "Place one heel on a low box or bench with the knee softly straight. Hinge forward over that leg until the back of the thigh begins to lengthen evenly.",
  },
  {
    id: "doorway-lat-hang-stretch",
    name: "Doorway Lat Hang Stretch",
    targetAreas: ["Lats", "Shoulders", "Side body"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Doorframe or pull-up bar support",
    bestFor: ["Overhead mobility", "Upper-body recovery"],
    coachingCue: "Sit the hips back and let the ribs soften so the stretch travels from the hand through the side body.",
    howTo: "Grab a doorway or stable overhead support with one hand and hinge the hips back while leaning away. Hold where the lat, shoulder, and side torso begin to lengthen.",
  },
  {
    id: "lizard-lunge-hip-stretch",
    name: "Lizard Lunge Hip Stretch",
    targetAreas: ["Hip flexors", "Adductors", "Hamstrings"],
    bodyPosition: "Split stance",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Warm-up prep", "Front-hip mobility"],
    coachingCue: "Let the back leg stay long and ease the elbows or hands inside the front foot without collapsing the chest.",
    howTo: "Step into a deep lunge and place both hands inside the front foot. Lower the hips gradually until the front hip, inner thigh, and back-leg hip flexor begin to open.",
  },
  {
    id: "pigeon-glute-stretch",
    name: "Pigeon Glute Stretch",
    targetAreas: ["Glutes", "Piriformis", "Posterior hip"],
    bodyPosition: "Prone",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Hip opening", "Post-leg-day recovery"],
    coachingCue: "Square the hips as much as you can and fold forward only after the front hip feels supported.",
    howTo: "Bring one shin forward across the body from a plank or quadruped position and extend the other leg back behind you. Stay upright or fold forward until the front glute and deep hip begin to release.",
  },
  {
    id: "shin-box-forward-fold",
    name: "Shin Box Forward Fold",
    targetAreas: ["Glutes", "Hip rotators", "Posterior hip"],
    bodyPosition: "Seated",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Hip rotation mobility", "Cooldown reset"],
    coachingCue: "Sit tall first and fold over the front shin without letting the back hip roll off the floor.",
    howTo: "Set up in a shin-box or 90/90 position and hinge the torso over the front shin. Hold where the outside of the front hip and glute begin to open without forcing the knee.",
  },
  {
    id: "quadruped-cat-tail-side-bend",
    name: "Quadruped Cat-Tail Side Bend",
    targetAreas: ["Side body", "Lats", "Quadratus lumborum"],
    bodyPosition: "Quadruped",
    durationGuidance: "4-6 slow reps per side",
    equipment: "Bodyweight",
    bestFor: ["Spinal mobility", "Breathing reset"],
    coachingCue: "Reach the head and hips toward each other in a smooth side bend instead of twisting through the shoulders.",
    howTo: "Start on hands and knees, then draw one hip and the head gently toward the same side to create a side bend through the torso. Alternate sides slowly, breathing into the long side of the body.",
  },
  {
    id: "toe-yoga-mobility",
    name: "Toe Yoga Mobility",
    targetAreas: ["Toes", "Arches", "Forefoot"],
    bodyPosition: "Seated",
    durationGuidance: "6-8 slow reps per side",
    equipment: "Chair or bench",
    bestFor: ["Foot control", "Warm-up prep"],
    coachingCue: "Move the big toe and the smaller toes separately without letting the ankle roll inward or outward.",
    howTo: "Sit with the foot planted and alternate lifting the big toe while the other toes stay down, then lifting the smaller toes while the big toe stays grounded. Move slowly through clean reps instead of rushing.",
  },
  {
    id: "supported-wall-split-calf-stretch",
    name: "Supported Wall Split Calf Stretch",
    targetAreas: ["Calves", "Achilles", "Ankles"],
    bodyPosition: "Split stance",
    durationGuidance: "20-30 sec per side",
    equipment: "Wall",
    bestFor: ["Lower-leg recovery", "Run and squat prep"],
    coachingCue: "Drive through the back heel and keep the back knee straight so the stretch stays high in the calf.",
    howTo: "Face a wall in a split stance and press both hands into the wall. Keep the back heel heavy and the back knee straight while the hips glide forward until the calf and Achilles begin to lengthen.",
  },
  {
    id: "bench-supported-pec-biceps-opener",
    name: "Bench-Supported Pec and Biceps Opener",
    targetAreas: ["Chest", "Biceps", "Front shoulder"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Bench or upright support",
    bestFor: ["Upper-body cooldown", "Posture reset"],
    coachingCue: "Open the chest gradually and keep the shoulder low instead of cranking the arm behind the body.",
    howTo: "Place one arm on a bench or upright with the palm open and elbow softly straight. Rotate the chest away until the chest, biceps, and front shoulder begin to open.",
  },
  {
    id: "bench-supported-calf-ankle-rock",
    name: "Bench-Supported Calf and Ankle Rock",
    targetAreas: ["Ankles", "Calves", "Achilles"],
    bodyPosition: "Standing",
    durationGuidance: "6-8 slow reps per side",
    equipment: "Bench or wall support",
    bestFor: ["Warm-up prep", "Ankle mobility"],
    coachingCue: "Keep the heel planted and let the knee travel forward under control instead of bouncing off the end range.",
    howTo: "Hold a support and step one foot forward. Rock the front knee forward over the toes and back out again while the heel stays grounded, using a smooth range that opens the ankle and calf.",
  },
  {
    id: "supine-figure-four-reach",
    name: "Supine Figure-Four Reach",
    targetAreas: ["Glutes", "Piriformis", "Outer hip"],
    bodyPosition: "Supine",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Hip reset", "Post-lifting recovery"],
    coachingCue: "Reach through the opening between the legs and pull the support thigh in without curling the neck off the floor.",
    howTo: "Lie on your back, cross one ankle over the opposite thigh, and thread the hands behind the support leg. Draw it in gently until the glute and outer hip of the crossed leg begin to open.",
  },
];

function normalizeStretchValue(value: string | null | undefined) {
  return typeof value === "string" ? value.trim().toLowerCase() : "";
}

export function isStretchHubExercise(exercise: StretchHubExerciseLike | null | undefined) {
  if (!exercise) {
    return false;
  }

  const normalizedSlug = normalizeStretchValue(exercise.slug);
  if (normalizedSlug === "stretch") {
    return true;
  }

  const normalizedName = normalizeStretchValue(exercise.name);
  if (normalizedName === "stretch") {
    return true;
  }

  return normalizeStretchValue(exercise.primary_muscle) === "recovery" && normalizedName.includes("stretch");
}

export function getStretchHubMetaItems() {
  return [...STRETCH_HUB_META_ITEMS];
}

export function getStretchHubChipLabels() {
  return [...STRETCH_HUB_CHIP_LABELS];
}

export function getStretchHubSummary(
  context: "browser" | "picker" | "planned" | "today" | "session" | "detail" = "browser",
) {
  switch (context) {
    case "picker":
      return "Mobility and recovery guide";
    case "planned":
      return null;
    case "today":
      return null;
    case "session":
      return null;
    case "detail":
      return STRETCH_HUB_GUIDE_COPY;
    default:
      return null;
  }
}
