import type { StretchReferenceSummary } from "@/lib/stretch-library-types";

export const STRETCH_LIBRARY_SUMMARIES: StretchReferenceSummary[] = [
  {
    id: "half-kneeling-hip-flexor-stretch",
    name: "Half-Kneeling Hip Flexor Stretch",
    targetAreas: ["Hip flexors", "Front thigh", "Anterior hip"],
    bodyPosition: "Half kneeling",
    durationGuidance: "20-40 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Lower-body warm-up", "Post-run reset"],
  },
  {
    id: "thomas-hip-flexor-stretch",
    name: "Thomas Hip Flexor Stretch",
    targetAreas: ["Hip flexors", "Quads", "Anterior hip"],
    bodyPosition: "Supine",
    durationGuidance: "20-30 sec per side",
    equipment: "Bench or sturdy box",
    bestFor: ["Desk posture reset", "Front-hip mobility"],
  },
  {
    id: "seated-hamstring-reach",
    name: "Seated Hamstring Reach",
    targetAreas: ["Hamstrings", "Calves", "Posterior chain"],
    bodyPosition: "Seated",
    durationGuidance: "20-45 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Lower-body cooldown", "Mobility reset"],
  },
  {
    id: "supine-hamstring-strap-stretch",
    name: "Supine Hamstring Strap Stretch",
    targetAreas: ["Hamstrings", "Calves", "Posterior chain"],
    bodyPosition: "Supine",
    durationGuidance: "20-40 sec per side",
    equipment: "Strap or towel",
    bestFor: ["Post-leg-day recovery", "Gentle flexibility work"],
  },
  {
    id: "sprinter-hamstring-stretch",
    name: "Sprinter Hamstring Stretch",
    targetAreas: ["Hamstrings", "Calves", "Posterior chain"],
    bodyPosition: "Half kneeling",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Warm-up prep", "Running mobility"],
  },
  {
    id: "doorway-pec-stretch",
    name: "Doorway Pec Stretch",
    targetAreas: ["Chest", "Front shoulder", "Biceps"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Doorway or upright post",
    bestFor: ["Upper-body recovery", "Desk posture reset"],
  },
  {
    id: "wall-pec-minor-stretch",
    name: "Wall Pec Minor Stretch",
    targetAreas: ["Chest", "Front shoulder", "Pec minor"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Wall or upright post",
    bestFor: ["Desk posture reset", "Upper-body recovery"],
  },
  {
    id: "doorway-biceps-stretch",
    name: "Doorway Biceps Stretch",
    targetAreas: ["Biceps", "Chest", "Front shoulder"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Doorway or upright post",
    bestFor: ["Upper-body cooldown", "Pull-day recovery"],
  },
  {
    id: "cross-body-posterior-shoulder-stretch",
    name: "Cross-Body Posterior Shoulder Stretch",
    targetAreas: ["Rear shoulder", "Upper back", "Posterior shoulder"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Upper-body cooldown", "Throwing-sport recovery"],
  },
  {
    id: "side-lying-shoulder-capsule-stretch",
    name: "Side-Lying Shoulder Capsule Stretch",
    targetAreas: ["Rear shoulder", "Rotator cuff", "Posterior shoulder"],
    bodyPosition: "Side lying",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Throwing-sport recovery", "Pressing recovery"],
  },
  {
    id: "overhead-triceps-stretch",
    name: "Overhead Triceps Stretch",
    targetAreas: ["Triceps", "Lats", "Shoulders"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Upper-body recovery", "Overhead mobility reset"],
  },
  {
    id: "standing-side-bend-lat-stretch",
    name: "Standing Side-Bend Lat Stretch",
    targetAreas: ["Lats", "Obliques", "Side body"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Overhead training prep", "Full-body reset"],
  },
  {
    id: "standing-lat-wall-stretch",
    name: "Standing Lat Wall Stretch",
    targetAreas: ["Lats", "Shoulders", "Side body"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Wall or upright post",
    bestFor: ["Overhead mobility", "Upper-body warm-up"],
  },
  {
    id: "childs-pose-lat-reach",
    name: "Child's Pose Lat Reach",
    targetAreas: ["Lats", "Upper back", "Triceps"],
    bodyPosition: "Kneeling",
    durationGuidance: "30-45 sec",
    equipment: "Bodyweight",
    bestFor: ["Overhead training reset", "Breathing reset"],
  },
  {
    id: "kneeling-bench-lat-stretch",
    name: "Kneeling Bench Lat Stretch",
    targetAreas: ["Lats", "Upper back", "Shoulders"],
    bodyPosition: "Kneeling",
    durationGuidance: "30-45 sec",
    equipment: "Bench",
    bestFor: ["Shoulder flexion mobility", "Upper-body cooldown"],
  },
  {
    id: "childs-pose-side-reach",
    name: "Child's Pose Side Reach",
    targetAreas: ["Lats", "Obliques", "Side body"],
    bodyPosition: "Kneeling",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Breathing reset", "Side-body mobility"],
  },
  {
    id: "figure-4-glute-stretch",
    name: "Figure-4 Glute Stretch",
    targetAreas: ["Glutes", "Piriformis", "Posterior hip"],
    bodyPosition: "Supine",
    durationGuidance: "20-40 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Post-leg-day recovery", "Hip rotation reset"],
  },
  {
    id: "ninety-ninety-hip-stretch",
    name: "90/90 Hip Stretch",
    targetAreas: ["Glutes", "Hip rotators", "Posterior hip"],
    bodyPosition: "Seated",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Hip rotation mobility", "Warm-up prep"],
  },
  {
    id: "kneeling-groin-rockback",
    name: "Kneeling Groin Rockback",
    targetAreas: ["Adductors", "Groin", "Inner thigh"],
    bodyPosition: "Quadruped",
    durationGuidance: "6-8 slow reps per side",
    equipment: "Bodyweight",
    bestFor: ["Adductor mobility", "Warm-up prep"],
  },
  {
    id: "reclined-butterfly-stretch",
    name: "Reclined Butterfly Stretch",
    targetAreas: ["Adductors", "Groin", "Anterior hips"],
    bodyPosition: "Supine",
    durationGuidance: "20-30 sec",
    equipment: "Bodyweight",
    bestFor: ["Cooldown reset", "Gentle hip opening"],
  },
  {
    id: "supine-spinal-twist",
    name: "Supine Spinal Twist",
    targetAreas: ["Mid-back", "Glutes", "Outer hip"],
    bodyPosition: "Supine",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Cooldown reset", "Rotational mobility"],
  },
  {
    id: "cat-cow-spinal-mobility",
    name: "Cat-Cow Spinal Mobility",
    targetAreas: ["Thoracic spine", "Low back", "Shoulders"],
    bodyPosition: "Quadruped",
    durationGuidance: "5-8 slow reps",
    equipment: "Bodyweight",
    bestFor: ["Warm-up prep", "Spinal mobility reset"],
  },
  {
    id: "knees-to-chest-stretch",
    name: "Knees-to-Chest Stretch",
    targetAreas: ["Low back", "Glutes", "Posterior chain"],
    bodyPosition: "Supine",
    durationGuidance: "20-30 sec",
    equipment: "Bodyweight",
    bestFor: ["Cooldown reset", "Low-back decompression"],
  },
  {
    id: "seated-forward-fold",
    name: "Seated Forward Fold",
    targetAreas: ["Hamstrings", "Calves", "Low back"],
    bodyPosition: "Seated",
    durationGuidance: "20-30 sec",
    equipment: "Bodyweight",
    bestFor: ["Cooldown mobility", "Posterior-chain reset"],
  },
  {
    id: "sphinx-abdominal-stretch",
    name: "Sphinx Abdominal Stretch",
    targetAreas: ["Abdominals", "Hip flexors", "Front body"],
    bodyPosition: "Prone",
    durationGuidance: "15-25 sec",
    equipment: "Bodyweight",
    bestFor: ["Front-body opening", "Post-sitting reset"],
  },
  {
    id: "standing-calf-wall-stretch",
    name: "Standing Calf Wall Stretch",
    targetAreas: ["Calves", "Achilles", "Ankles"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Wall",
    bestFor: ["Run prep", "Lower-leg recovery"],
  },
  {
    id: "bent-knee-soleus-wall-stretch",
    name: "Bent-Knee Soleus Wall Stretch",
    targetAreas: ["Soleus", "Achilles", "Ankles"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Wall",
    bestFor: ["Ankle mobility", "Run and squat prep"],
  },
  {
    id: "kneeling-ankle-dorsiflexion-stretch",
    name: "Kneeling Ankle Dorsiflexion Stretch",
    targetAreas: ["Ankles", "Achilles", "Calves"],
    bodyPosition: "Half kneeling",
    durationGuidance: "8-10 slow reps per side",
    equipment: "Wall",
    bestFor: ["Squat prep", "Running mobility"],
  },
  {
    id: "standing-tibialis-anterior-stretch",
    name: "Standing Tibialis Anterior Stretch",
    targetAreas: ["Shins", "Ankles", "Top of foot"],
    bodyPosition: "Standing",
    durationGuidance: "15-25 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Lower-leg recovery", "Running cooldown"],
  },
  {
    id: "open-book-thoracic-rotation",
    name: "Open Book Thoracic Rotation",
    targetAreas: ["Mid-back", "Chest", "Shoulder girdle"],
    bodyPosition: "Side lying",
    durationGuidance: "5-8 slow reps per side",
    equipment: "Bodyweight",
    bestFor: ["Upper-body warm-up", "Rotation mobility"],
  },
  {
    id: "thread-the-needle-rotation",
    name: "Thread-the-Needle Rotation",
    targetAreas: ["Mid-back", "Rear shoulder", "Upper back"],
    bodyPosition: "Quadruped",
    durationGuidance: "5-8 slow reps per side",
    equipment: "Bodyweight",
    bestFor: ["Thoracic mobility", "Upper-body warm-up"],
  },
  {
    id: "seated-thoracic-extension-chair",
    name: "Seated Thoracic Extension Stretch",
    targetAreas: ["Thoracic spine", "Chest", "Upper back"],
    bodyPosition: "Seated",
    durationGuidance: "5-8 slow reps",
    equipment: "Chair or bench",
    bestFor: ["Desk posture reset", "Upper-body warm-up"],
  },
  {
    id: "prone-cobra-chest-opener",
    name: "Prone Cobra Chest Opener",
    targetAreas: ["Chest", "Front shoulders", "Thoracic spine"],
    bodyPosition: "Prone",
    durationGuidance: "15-25 sec",
    equipment: "Bodyweight",
    bestFor: ["Posture reset", "Upper-body recovery"],
  },
  {
    id: "couch-quad-stretch",
    name: "Couch Quad Stretch",
    targetAreas: ["Quads", "Hip flexors", "Front thigh"],
    bodyPosition: "Kneeling",
    durationGuidance: "20-30 sec per side",
    equipment: "Wall or bench",
    bestFor: ["Post-squat recovery", "Front-thigh mobility"],
  },
  {
    id: "standing-quadriceps-stretch",
    name: "Standing Quadriceps Stretch",
    targetAreas: ["Quads", "Hip flexors", "Front thigh"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Wall or support",
    bestFor: ["Pre-run mobility", "Lower-body cooldown"],
  },
  {
    id: "prone-quad-stretch",
    name: "Prone Quad Stretch",
    targetAreas: ["Quads", "Front thigh", "Hip flexors"],
    bodyPosition: "Prone",
    durationGuidance: "20-30 sec per side",
    equipment: "Strap or towel",
    bestFor: ["Post-leg-day recovery", "Gentle front-thigh mobility"],
  },
  {
    id: "static-standing-adductor-stretch",
    name: "Static Standing Adductor Stretch",
    targetAreas: ["Adductors", "Groin", "Inner thigh"],
    bodyPosition: "Standing",
    durationGuidance: "15-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Lateral movement prep", "Hip mobility"],
  },
  {
    id: "frog-adductor-stretch",
    name: "Frog Adductor Stretch",
    targetAreas: ["Adductors", "Groin", "Inner thighs"],
    bodyPosition: "Quadruped",
    durationGuidance: "20-30 sec",
    equipment: "Bodyweight",
    bestFor: ["Hip opening", "Adductor mobility"],
  },
  {
    id: "butterfly-groin-stretch",
    name: "Butterfly Groin Stretch",
    targetAreas: ["Adductors", "Groin", "Inner thigh"],
    bodyPosition: "Seated",
    durationGuidance: "20-30 sec",
    equipment: "Bodyweight",
    bestFor: ["Hip opening", "Cooldown mobility"],
  },
  {
    id: "worlds-greatest-stretch",
    name: "World's Greatest Stretch",
    targetAreas: ["Hip flexors", "Hamstrings", "Thoracic spine"],
    bodyPosition: "Split stance",
    durationGuidance: "4-6 slow reps per side",
    equipment: "Bodyweight",
    bestFor: ["Dynamic warm-up", "Full-body mobility"],
  },
  {
    id: "low-lunge-reach-and-rotate",
    name: "Low Lunge Reach and Rotate",
    targetAreas: ["Hip flexors", "Thoracic spine", "Side body"],
    bodyPosition: "Half kneeling",
    durationGuidance: "4-6 slow reps per side",
    equipment: "Bodyweight",
    bestFor: ["Dynamic warm-up", "Full-body mobility"],
  },
  {
    id: "wall-shoulder-flexion-stretch",
    name: "Wall Shoulder Flexion Stretch",
    targetAreas: ["Shoulders", "Lats", "Triceps"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Wall",
    bestFor: ["Overhead mobility", "Pressing warm-up"],
  },
  {
    id: "wrist-flexor-wall-stretch",
    name: "Wrist Flexor Wall Stretch",
    targetAreas: ["Forearm flexors", "Wrists", "Palms"],
    bodyPosition: "Standing",
    durationGuidance: "15-25 sec per side",
    equipment: "Wall",
    bestFor: ["Grip recovery", "Upper-body cooldown"],
  },
  {
    id: "kneeling-toe-flexor-stretch",
    name: "Kneeling Toe Flexor Stretch",
    targetAreas: ["Toes", "Plantar fascia", "Arches"],
    bodyPosition: "Kneeling",
    durationGuidance: "15-25 sec",
    equipment: "Bodyweight",
    bestFor: ["Foot mobility", "Running recovery"],
  },
  {
    id: "standing-plantar-fascia-stretch",
    name: "Standing Plantar Fascia Stretch",
    targetAreas: ["Plantar fascia", "Arches", "Toes"],
    bodyPosition: "Standing",
    durationGuidance: "15-25 sec per side",
    equipment: "Wall or step",
    bestFor: ["Foot recovery", "Morning mobility"],
  },
  {
    id: "wrist-extensor-wall-stretch",
    name: "Wrist Extensor Wall Stretch",
    targetAreas: ["Forearm extensors", "Wrists", "Top of forearm"],
    bodyPosition: "Standing",
    durationGuidance: "15-25 sec per side",
    equipment: "Wall",
    bestFor: ["Typing reset", "Grip-heavy training recovery"],
  },
  {
    id: "prayer-wrist-stretch",
    name: "Prayer Wrist Stretch",
    targetAreas: ["Wrists", "Forearm flexors", "Palms"],
    bodyPosition: "Standing",
    durationGuidance: "15-25 sec",
    equipment: "Bodyweight",
    bestFor: ["Typing reset", "Grip recovery"],
  },
  {
    id: "seated-upper-trap-stretch",
    name: "Seated Upper Trap Stretch",
    targetAreas: ["Upper traps", "Neck", "Shoulders"],
    bodyPosition: "Seated",
    durationGuidance: "15-25 sec per side",
    equipment: "Chair",
    bestFor: ["Desk reset", "Neck tension relief"],
  },
  {
    id: "levator-scapulae-stretch",
    name: "Levator Scapulae Stretch",
    targetAreas: ["Neck", "Upper traps", "Rear shoulder"],
    bodyPosition: "Seated",
    durationGuidance: "15-25 sec per side",
    equipment: "Chair",
    bestFor: ["Desk posture reset", "Overhead training recovery"],
  },
  {
    id: "seated-neck-rotation-stretch",
    name: "Seated Neck Rotation Stretch",
    targetAreas: ["Neck", "Scalenes", "Upper traps"],
    bodyPosition: "Seated",
    durationGuidance: "15-20 sec per side",
    equipment: "Chair",
    bestFor: ["Desk reset", "Driving stiffness relief"],
  },
  {
    id: "standing-tfl-crossover-stretch",
    name: "Standing TFL Crossover Stretch",
    targetAreas: ["Tensor fasciae latae", "Lateral hip", "Outer thigh"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Wall or support",
    bestFor: ["Running recovery", "Lateral hip mobility"],
  },
  {
    id: "seated-piriformis-stretch",
    name: "Seated Piriformis Stretch",
    targetAreas: ["Piriformis", "Glutes", "Posterior hip"],
    bodyPosition: "Seated",
    durationGuidance: "20-30 sec per side",
    equipment: "Chair or bench",
    bestFor: ["Desk reset", "Hip rotation mobility"],
  },
  {
    id: "single-knee-to-chest-stretch",
    name: "Single Knee-to-Chest Stretch",
    targetAreas: ["Glutes", "Low back", "Posterior hip"],
    bodyPosition: "Supine",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Cooldown reset", "Gentle low-back relief"],
  },
  {
    id: "happy-baby-hip-stretch",
    name: "Happy Baby Hip Stretch",
    targetAreas: ["Adductors", "Glutes", "Posterior hip"],
    bodyPosition: "Supine",
    durationGuidance: "20-30 sec",
    equipment: "Bodyweight",
    bestFor: ["Hip opening", "Recovery reset"],
  },
  {
    id: "wide-leg-seated-forward-fold",
    name: "Wide-Leg Seated Forward Fold",
    targetAreas: ["Hamstrings", "Adductors", "Posterior chain"],
    bodyPosition: "Seated",
    durationGuidance: "20-40 sec",
    equipment: "Bodyweight",
    bestFor: ["Lower-body cooldown", "Straddle mobility"],
  },
  {
    id: "cossack-adductor-rock",
    name: "Cossack Adductor Rock",
    targetAreas: ["Adductors", "Groin", "Ankles"],
    bodyPosition: "Standing",
    durationGuidance: "5-6 slow reps per side",
    equipment: "Bodyweight",
    bestFor: ["Dynamic warm-up", "Lateral movement prep"],
  },
  {
    id: "quadratus-lumborum-doorway-stretch",
    name: "Quadratus Lumborum Doorway Stretch",
    targetAreas: ["Quadratus lumborum", "Side body", "Obliques"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Doorframe or upright post",
    bestFor: ["Side-body reset", "Post-lifting recovery"],
  },
  {
    id: "bear-hug-rhomboid-stretch",
    name: "Bear-Hug Rhomboid Stretch",
    targetAreas: ["Rhomboids", "Upper back", "Rear shoulders"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec",
    equipment: "Bodyweight",
    bestFor: ["Upper-back reset", "Posture recovery"],
  },
  {
    id: "wall-serratus-reach-stretch",
    name: "Wall Serratus Reach Stretch",
    targetAreas: ["Serratus anterior", "Lats", "Upper ribs"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Wall",
    bestFor: ["Overhead prep", "Upper-body mobility"],
  },
  {
    id: "lateral-calf-peroneal-stretch",
    name: "Lateral Calf Peroneal Stretch",
    targetAreas: ["Peroneals", "Outer calf", "Ankles"],
    bodyPosition: "Standing",
    durationGuidance: "15-25 sec per side",
    equipment: "Wall or support",
    bestFor: ["Ankle mobility", "Running recovery"],
  },
  {
    id: "standing-side-body-doorframe-stretch",
    name: "Standing Side-Body Doorframe Stretch",
    targetAreas: ["Side body", "Lats", "Obliques"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Doorframe or upright post",
    bestFor: ["Breathing reset", "Full-body mobility"],
  },
  {
    id: "supine-crossover-lateral-hip-stretch",
    name: "Supine Crossover Lateral Hip Stretch",
    targetAreas: ["Outer hip", "Glute medius", "Lateral hip"],
    bodyPosition: "Supine",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Hip reset", "Lower-body recovery"],
  },
  {
    id: "puppy-pose-shoulder-stretch",
    name: "Puppy Pose Shoulder Stretch",
    targetAreas: ["Shoulders", "Lats", "Upper back"],
    bodyPosition: "Kneeling",
    durationGuidance: "20-30 sec",
    equipment: "Bodyweight",
    bestFor: ["Overhead mobility", "Upper-body cooldown"],
  },
  {
    id: "thread-the-needle-shoulder-stretch",
    name: "Thread-the-Needle Shoulder Stretch",
    targetAreas: ["Rear shoulder", "Thoracic spine", "Upper back"],
    bodyPosition: "Quadruped",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Upper-back mobility", "Pressing recovery"],
  },
  {
    id: "kneeling-triceps-bench-stretch",
    name: "Kneeling Triceps Bench Stretch",
    targetAreas: ["Triceps", "Lats", "Shoulders"],
    bodyPosition: "Kneeling",
    durationGuidance: "20-30 sec",
    equipment: "Bench or box",
    bestFor: ["Overhead mobility", "Upper-body cooldown"],
  },
  {
    id: "wall-external-rotation-shoulder-stretch",
    name: "Wall External Rotation Shoulder Stretch",
    targetAreas: ["Rotator cuff", "Front shoulder", "Chest"],
    bodyPosition: "Standing",
    durationGuidance: "15-25 sec per side",
    equipment: "Wall",
    bestFor: ["Shoulder prep", "Pressing mobility"],
  },
  {
    id: "strap-shoulder-extension-stretch",
    name: "Strap Shoulder Extension Stretch",
    targetAreas: ["Front shoulders", "Biceps", "Chest"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec",
    equipment: "Strap or towel",
    bestFor: ["Desk posture reset", "Upper-body recovery"],
  },
  {
    id: "seated-straddle-side-reach",
    name: "Seated Straddle Side Reach",
    targetAreas: ["Adductors", "Side body", "Hamstrings"],
    bodyPosition: "Seated",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Straddle mobility", "Cooldown reset"],
  },
  {
    id: "half-kneeling-hip-internal-rotation-stretch",
    name: "Half-Kneeling Hip Internal Rotation Stretch",
    targetAreas: ["Hip internal rotators", "Glutes", "Posterior hip"],
    bodyPosition: "Half kneeling",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Hip rotation mobility", "Warm-up prep"],
  },
  {
    id: "ninety-ninety-switch-flow",
    name: "90/90 Switch Flow",
    targetAreas: ["Hip rotators", "Glutes", "Anterior hip"],
    bodyPosition: "Seated",
    durationGuidance: "4-6 slow reps per side",
    equipment: "Bodyweight",
    bestFor: ["Dynamic warm-up", "Hip mobility"],
  },
  {
    id: "kneeling-shin-top-foot-stretch",
    name: "Kneeling Shin and Top-of-Foot Stretch",
    targetAreas: ["Shins", "Top of foot", "Ankles"],
    bodyPosition: "Kneeling",
    durationGuidance: "15-25 sec",
    equipment: "Bodyweight",
    bestFor: ["Foot mobility", "Ankle reset"],
  },
  {
    id: "seated-toe-extension-stretch",
    name: "Seated Toe Extension Stretch",
    targetAreas: ["Toes", "Plantar fascia", "Forefoot"],
    bodyPosition: "Seated",
    durationGuidance: "15-20 sec per side",
    equipment: "Chair or bench",
    bestFor: ["Foot recovery", "Walking comfort reset"],
  },
  {
    id: "sternocleidomastoid-stretch",
    name: "Sternocleidomastoid Stretch",
    targetAreas: ["Neck", "Scalenes", "Front of neck"],
    bodyPosition: "Seated",
    durationGuidance: "15-20 sec per side",
    equipment: "Chair",
    bestFor: ["Desk reset", "Neck tension relief"],
  },
  {
    id: "forearm-pronation-stretch",
    name: "Forearm Pronation Stretch",
    targetAreas: ["Forearm pronators", "Wrists", "Elbows"],
    bodyPosition: "Standing",
    durationGuidance: "15-20 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Grip recovery", "Elbow comfort reset"],
  },
  {
    id: "forearm-supination-stretch",
    name: "Forearm Supination Stretch",
    targetAreas: ["Forearm supinators", "Wrists", "Elbows"],
    bodyPosition: "Standing",
    durationGuidance: "15-20 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Grip recovery", "Elbow comfort reset"],
  },
  {
    id: "standing-it-band-side-reach",
    name: "Standing IT Band Side Reach",
    targetAreas: ["Outer thigh", "Lateral hip", "Side body"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Wall or support",
    bestFor: ["Lateral line mobility", "Run and squat recovery"],
  },
  {
    id: "wall-angel-shoulder-mobility",
    name: "Wall Angel Shoulder Mobility",
    targetAreas: ["Chest", "Shoulders", "Upper back"],
    bodyPosition: "Standing",
    durationGuidance: "6-8 slow reps",
    equipment: "Wall",
    bestFor: ["Posture reset", "Upper-body warm-up"],
  },
  {
    id: "side-lying-windmill-stretch",
    name: "Side-Lying Windmill Stretch",
    targetAreas: ["Thoracic spine", "Chest", "Front shoulder"],
    bodyPosition: "Side lying",
    durationGuidance: "4-6 slow reps per side",
    equipment: "Bodyweight",
    bestFor: ["Thoracic mobility", "Warm-up prep"],
  },
  {
    id: "deep-squat-pry-hold",
    name: "Deep Squat Pry Hold",
    targetAreas: ["Ankles", "Adductors", "Hips"],
    bodyPosition: "Squat",
    durationGuidance: "20-30 sec",
    equipment: "Bodyweight or support",
    bestFor: ["Lower-body mobility", "Pre-lift prep"],
  },
  {
    id: "half-kneeling-adductor-glide",
    name: "Half-Kneeling Adductor Glide",
    targetAreas: ["Adductors", "Groin", "Inner thigh"],
    bodyPosition: "Half kneeling",
    durationGuidance: "5-6 slow reps per side",
    equipment: "Bodyweight",
    bestFor: ["Dynamic warm-up", "Groin prep"],
  },
  {
    id: "rear-delt-doorway-stretch",
    name: "Rear Delt Doorway Stretch",
    targetAreas: ["Rear shoulder", "Upper back", "Posterior shoulder"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Doorway or upright post",
    bestFor: ["Upper-body recovery", "Post-pull-day reset"],
  },
  {
    id: "reverse-prayer-forearm-stretch",
    name: "Reverse Prayer Forearm Stretch",
    targetAreas: ["Wrists", "Forearm extensors", "Forearms"],
    bodyPosition: "Standing",
    durationGuidance: "15-20 sec",
    equipment: "Bodyweight",
    bestFor: ["Desk reset", "Grip recovery"],
  },
  {
    id: "seated-calf-strap-stretch",
    name: "Seated Calf Strap Stretch",
    targetAreas: ["Calves", "Achilles", "Hamstrings"],
    bodyPosition: "Seated",
    durationGuidance: "20-30 sec per side",
    equipment: "Strap or towel",
    bestFor: ["Run recovery", "Lower-leg flexibility"],
  },
  {
    id: "ankle-inversion-eversion-mobility",
    name: "Ankle Inversion and Eversion Mobility",
    targetAreas: ["Ankles", "Peroneals", "Inner ankle"],
    bodyPosition: "Seated",
    durationGuidance: "6-8 slow reps per side",
    equipment: "Chair or bench",
    bestFor: ["Ankle control", "Foot mobility"],
  },
  {
    id: "side-lying-banana-stretch",
    name: "Side-Lying Banana Stretch",
    targetAreas: ["Side body", "Lats", "Outer hip"],
    bodyPosition: "Supine",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Breathing reset", "Full-body recovery"],
  },
  {
    id: "scorpion-thoracic-rotation",
    name: "Scorpion Thoracic Rotation",
    targetAreas: ["Thoracic spine", "Hip flexors", "Front body"],
    bodyPosition: "Prone",
    durationGuidance: "4-6 slow reps per side",
    equipment: "Bodyweight",
    bestFor: ["Dynamic warm-up", "Rotational mobility"],
  },
  {
    id: "foam-roll-chest-opener-stretch",
    name: "Foam Roll Chest Opener Stretch",
    targetAreas: ["Chest", "Front shoulders", "Thoracic spine"],
    bodyPosition: "Supine",
    durationGuidance: "20-40 sec",
    equipment: "Foam roller",
    bestFor: ["Upper-body recovery", "Posture reset"],
  },
  {
    id: "groiner-lunge-stretch",
    name: "Groiner Lunge Stretch",
    targetAreas: ["Adductors", "Hip flexors", "Hamstrings"],
    bodyPosition: "Split stance",
    durationGuidance: "4-6 slow reps per side",
    equipment: "Bodyweight",
    bestFor: ["Dynamic warm-up", "Lower-body prep"],
  },
  {
    id: "sleeper-shoulder-stretch",
    name: "Sleeper Shoulder Stretch",
    targetAreas: ["Rear shoulder", "Rotator cuff", "Posterior shoulder"],
    bodyPosition: "Side lying",
    durationGuidance: "15-25 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Throwing recovery", "Shoulder internal-rotation mobility"],
  },
  {
    id: "heel-on-box-hamstring-stretch",
    name: "Heel-on-Box Hamstring Stretch",
    targetAreas: ["Hamstrings", "Calves", "Posterior chain"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Box or bench",
    bestFor: ["Lower-body cooldown", "Run and hinge recovery"],
  },
  {
    id: "doorway-lat-hang-stretch",
    name: "Doorway Lat Hang Stretch",
    targetAreas: ["Lats", "Shoulders", "Side body"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Doorframe or pull-up bar support",
    bestFor: ["Overhead mobility", "Upper-body recovery"],
  },
  {
    id: "lizard-lunge-hip-stretch",
    name: "Lizard Lunge Hip Stretch",
    targetAreas: ["Hip flexors", "Adductors", "Hamstrings"],
    bodyPosition: "Split stance",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Warm-up prep", "Front-hip mobility"],
  },
  {
    id: "pigeon-glute-stretch",
    name: "Pigeon Glute Stretch",
    targetAreas: ["Glutes", "Piriformis", "Posterior hip"],
    bodyPosition: "Prone",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Hip opening", "Post-leg-day recovery"],
  },
  {
    id: "shin-box-forward-fold",
    name: "Shin Box Forward Fold",
    targetAreas: ["Glutes", "Hip rotators", "Posterior hip"],
    bodyPosition: "Seated",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Hip rotation mobility", "Cooldown reset"],
  },
  {
    id: "quadruped-cat-tail-side-bend",
    name: "Quadruped Cat-Tail Side Bend",
    targetAreas: ["Side body", "Lats", "Quadratus lumborum"],
    bodyPosition: "Quadruped",
    durationGuidance: "4-6 slow reps per side",
    equipment: "Bodyweight",
    bestFor: ["Spinal mobility", "Breathing reset"],
  },
  {
    id: "toe-yoga-mobility",
    name: "Toe Yoga Mobility",
    targetAreas: ["Toes", "Arches", "Forefoot"],
    bodyPosition: "Seated",
    durationGuidance: "6-8 slow reps per side",
    equipment: "Chair or bench",
    bestFor: ["Foot control", "Warm-up prep"],
  },
  {
    id: "supported-wall-split-calf-stretch",
    name: "Supported Wall Split Calf Stretch",
    targetAreas: ["Calves", "Achilles", "Ankles"],
    bodyPosition: "Split stance",
    durationGuidance: "20-30 sec per side",
    equipment: "Wall",
    bestFor: ["Lower-leg recovery", "Run and squat prep"],
  },
  {
    id: "bench-supported-pec-biceps-opener",
    name: "Bench-Supported Pec and Biceps Opener",
    targetAreas: ["Chest", "Biceps", "Front shoulder"],
    bodyPosition: "Standing",
    durationGuidance: "20-30 sec per side",
    equipment: "Bench or upright support",
    bestFor: ["Upper-body cooldown", "Posture reset"],
  },
  {
    id: "bench-supported-calf-ankle-rock",
    name: "Bench-Supported Calf and Ankle Rock",
    targetAreas: ["Ankles", "Calves", "Achilles"],
    bodyPosition: "Standing",
    durationGuidance: "6-8 slow reps per side",
    equipment: "Bench or wall support",
    bestFor: ["Warm-up prep", "Ankle mobility"],
  },
  {
    id: "supine-figure-four-reach",
    name: "Supine Figure-Four Reach",
    targetAreas: ["Glutes", "Piriformis", "Outer hip"],
    bodyPosition: "Supine",
    durationGuidance: "20-30 sec per side",
    equipment: "Bodyweight",
    bestFor: ["Hip reset", "Post-lifting recovery"],
  },
];
