import { IconSpec } from "./iconSpec";

export const exerciseIconMap: Record<string, IconSpec> = {
  "ab-wheel-rollout": { kind: "core", equipment: "bodyweight", variant: "ab-wheel-rollout" },
  "abductor-machine": { kind: "machine_other", equipment: "machine", variant: "abductor-machine" },
  "adductor-machine": { kind: "machine_other", equipment: "machine", variant: "adductor-machine" },
  "air-bike-sprint": { kind: "cardio", equipment: "cardio", variant: "air-bike-sprint" },
  "alternating-dumbbell-curl": { kind: "curl", equipment: "dumbbell", grip: "supinated", variant: "alternating-dumbbell-curl" },
  "arnold-press": { kind: "overhead_press", equipment: "dumbbell", variant: "arnold-press" },
  "back-extension": { kind: "hinge", equipment: "bodyweight", stance: "normal", variant: "back-extension" },
  "back-squat": { kind: "squat", equipment: "barbell", stance: "normal", variant: "back-squat" },
  "barbell-bench-press": { kind: "bench", equipment: "barbell", angle: "flat", variant: "barbell-bench-press" },
  "barbell-curl": { kind: "curl", equipment: "barbell", grip: "supinated", variant: "barbell-curl" },
  "barbell-row": { kind: "row", equipment: "barbell", grip: "pronated", variant: "barbell-row" },
  "bench-press": { kind: "bench", equipment: "barbell", angle: "flat", variant: "bench-press" },
  "bulgarian-split-squat": { kind: "lunge", equipment: "bodyweight", unilateral: true, variant: "bulgarian-split-squat" },
  "cable-crunch": { kind: "core", equipment: "cable", cablePath: "straight", variant: "cable-crunch" },
  "cable-curl": { kind: "curl", equipment: "cable", grip: "supinated", cablePath: "straight", variant: "cable-curl" },
  "cable-fly": { kind: "fly", equipment: "cable", angle: "flat", cablePath: "straight", variant: "cable-fly" },
  "cable-kickback": { kind: "triceps", equipment: "cable", cablePath: "straight", variant: "cable-kickback" },
  "cable-lateral-raise": { kind: "overhead_press", equipment: "cable", cablePath: "straight", variant: "cable-lateral-raise" },
  "cable-rear-delt-fly": { kind: "fly", equipment: "cable", angle: "flat", cablePath: "straight", variant: "cable-rear-delt-fly" },
  "calf-raise-seated": { kind: "calf_raise", equipment: "machine", variant: "calf-raise-seated" },
  "calf-raise-standing": { kind: "calf_raise", equipment: "bodyweight", variant: "calf-raise-standing" },
  "chest-press": { kind: "bench", equipment: "machine", angle: "flat", variant: "chest-press" },
  "chest-supported-row": { kind: "row", equipment: "machine", grip: "pronated", variant: "chest-supported-row" },
  "chin-up": { kind: "pulldown", equipment: "bodyweight", grip: "supinated", variant: "chin-up" },
  "close-grip-bench-press": { kind: "bench", equipment: "barbell", angle: "flat", grip: "close", variant: "close-grip-bench-press" },
  "close-grip-lat-pulldown": { kind: "pulldown", equipment: "cable", grip: "close", cablePath: "straight", variant: "close-grip-lat-pulldown" },
  "close-grip-push-up": { kind: "bench", equipment: "bodyweight", angle: "flat", grip: "close", variant: "close-grip-push-up" },
  "concentration-curl": { kind: "curl", equipment: "dumbbell", grip: "supinated", variant: "concentration-curl" },
  "cross-body-hammer-curl": { kind: "curl", equipment: "dumbbell", grip: "neutral", variant: "cross-body-hammer-curl" },
  "dead-bug": { kind: "core", equipment: "bodyweight", variant: "dead-bug" },
  "deadlift": { kind: "hinge", equipment: "barbell", stance: "normal", variant: "deadlift" },
  "decline-barbell-bench-press": { kind: "bench", equipment: "barbell", angle: "decline", variant: "decline-barbell-bench-press" },
  "decline-dumbbell-bench-press": { kind: "bench", equipment: "dumbbell", angle: "decline", variant: "decline-dumbbell-bench-press" },
  "deficit-push-up": { kind: "bench", equipment: "bodyweight", angle: "flat", variant: "deficit-push-up" },
  "dips-chest": { kind: "bench", equipment: "bodyweight", angle: "flat", variant: "dips-chest" },
  "dips-triceps": { kind: "bench", equipment: "bodyweight", angle: "flat", variant: "dips-triceps" },
  "donkey-calf-raise": { kind: "calf_raise", equipment: "machine", variant: "donkey-calf-raise" },
  "dumbbell-bench-press": { kind: "bench", equipment: "dumbbell", angle: "flat", variant: "dumbbell-bench-press" },
  "dumbbell-curl": { kind: "curl", equipment: "dumbbell", grip: "supinated", variant: "dumbbell-curl" },
  "dumbbell-fly": { kind: "fly", equipment: "dumbbell", angle: "flat", variant: "dumbbell-fly" },
  "dumbbell-overhead-triceps-extension": { kind: "triceps", equipment: "dumbbell", variant: "dumbbell-overhead-triceps-extension" },
  "dumbbell-row": { kind: "row", equipment: "dumbbell", grip: "pronated", variant: "dumbbell-row" },
  "ez-bar-curl": { kind: "curl", equipment: "barbell", grip: "supinated", variant: "ez-bar-curl" },
  "face-pull": { kind: "row", equipment: "cable", grip: "neutral", cablePath: "straight", variant: "face-pull" },
  "front-raise": { kind: "overhead_press", equipment: "dumbbell", variant: "front-raise" },
  "front-squat": { kind: "squat", equipment: "barbell", stance: "normal", variant: "front-squat" },
  "glute-bridge": { kind: "hip_thrust", equipment: "bodyweight", variant: "glute-bridge" },
  "goblet-squat": { kind: "squat", equipment: "dumbbell", stance: "normal", variant: "goblet-squat" },
  "hack-squat": { kind: "squat", equipment: "machine", stance: "normal", variant: "hack-squat" },
  "hammer-curl": { kind: "curl", equipment: "dumbbell", grip: "neutral", variant: "hammer-curl" },
  "hanging-leg-raise": { kind: "core", equipment: "bodyweight", variant: "hanging-leg-raise" },
  "high-bar-back-squat": { kind: "squat", equipment: "barbell", stance: "normal", variant: "high-bar-back-squat" },
  "high-to-low-cable-fly": { kind: "fly", equipment: "cable", angle: "flat", cablePath: "high_to_low", variant: "high-to-low-cable-fly" },
  "hip-thrust": { kind: "hip_thrust", equipment: "barbell", variant: "hip-thrust" },
  "hollow-body-hold": { kind: "core", equipment: "bodyweight", variant: "hollow-body-hold" },
  "incline-barbell-bench-press": { kind: "bench", equipment: "barbell", angle: "incline", variant: "incline-barbell-bench-press" },
  "incline-dumbbell-bench-press": { kind: "bench", equipment: "dumbbell", angle: "incline", variant: "incline-dumbbell-bench-press" },
  "incline-dumbbell-curl": { kind: "curl", equipment: "dumbbell", grip: "supinated", variant: "incline-dumbbell-curl" },
  "incline-dumbbell-fly": { kind: "fly", equipment: "dumbbell", angle: "incline", variant: "incline-dumbbell-fly" },
  "incline-walk": { kind: "cardio", equipment: "cardio", variant: "incline-walk" },
  "jump-rope": { kind: "cardio", equipment: "cardio", variant: "jump-rope" },
  "lat-pulldown": { kind: "pulldown", equipment: "cable", grip: "pronated", cablePath: "straight", variant: "lat-pulldown" },
  "lateral-raise": { kind: "overhead_press", equipment: "dumbbell", variant: "lateral-raise" },
  "leaning-cable-lateral-raise": { kind: "overhead_press", equipment: "cable", cablePath: "straight", variant: "leaning-cable-lateral-raise" },
  "leg-extension": { kind: "machine_other", equipment: "machine", variant: "leg-extension" },
  "leg-press": { kind: "squat", equipment: "machine", stance: "normal", variant: "leg-press" },
  "low-bar-back-squat": { kind: "squat", equipment: "barbell", stance: "normal", variant: "low-bar-back-squat" },
  "low-to-high-cable-fly": { kind: "fly", equipment: "cable", angle: "flat", cablePath: "low_to_high", variant: "low-to-high-cable-fly" },
  "lying-leg-curl": { kind: "machine_other", equipment: "machine", grip: "supinated", variant: "lying-leg-curl" },
  "lying-leg-raise": { kind: "core", equipment: "bodyweight", variant: "lying-leg-raise" },
  "machine-biceps-curl": { kind: "curl", equipment: "machine", grip: "supinated", variant: "machine-biceps-curl" },
  "machine-crunch": { kind: "core", equipment: "machine", variant: "machine-crunch" },
  "machine-row": { kind: "row", equipment: "machine", grip: "pronated", variant: "machine-row" },
  "machine-shoulder-press": { kind: "overhead_press", equipment: "machine", variant: "machine-shoulder-press" },
  "neutral-grip-pull-up": { kind: "pulldown", equipment: "bodyweight", grip: "neutral", variant: "neutral-grip-pull-up" },
  "nordic-curl": { kind: "hinge", equipment: "bodyweight", stance: "normal", grip: "supinated", variant: "nordic-curl" },
  "overhead-press": { kind: "overhead_press", equipment: "barbell", variant: "overhead-press" },
  "overhead-triceps-extension": { kind: "triceps", equipment: "dumbbell", variant: "overhead-triceps-extension" },
  "pallof-press": { kind: "core", equipment: "cable", cablePath: "straight", variant: "pallof-press" },
  "paused-back-squat": { kind: "squat", equipment: "barbell", stance: "normal", variant: "paused-back-squat" },
  "paused-barbell-bench-press": { kind: "bench", equipment: "barbell", angle: "flat", variant: "paused-barbell-bench-press" },
  "paused-deadlift": { kind: "hinge", equipment: "barbell", stance: "normal", variant: "paused-deadlift" },
  "paused-front-squat": { kind: "squat", equipment: "barbell", stance: "normal", variant: "paused-front-squat" },
  "pec-deck": { kind: "fly", equipment: "machine", angle: "flat", variant: "pec-deck" },
  "pendlay-row": { kind: "row", equipment: "barbell", grip: "pronated", variant: "pendlay-row" },
  "plank": { kind: "core", equipment: "bodyweight", variant: "plank" },
  "plate-front-raise": { kind: "overhead_press", equipment: "barbell", variant: "plate-front-raise" },
  "preacher-curl": { kind: "curl", equipment: "machine", grip: "supinated", variant: "preacher-curl" },
  "pull-up": { kind: "pulldown", equipment: "bodyweight", grip: "pronated", variant: "pull-up" },
  "push-press": { kind: "overhead_press", equipment: "barbell", variant: "push-press" },
  "push-up": { kind: "bench", equipment: "bodyweight", angle: "flat", variant: "push-up" },
  "rack-pull": { kind: "hinge", equipment: "barbell", stance: "normal", variant: "rack-pull" },
  "rear-delt-fly": { kind: "fly", equipment: "dumbbell", angle: "flat", variant: "rear-delt-fly" },
  "reverse-hyperextension": { kind: "hinge", equipment: "bodyweight", stance: "normal", variant: "reverse-hyperextension" },
  "reverse-lunge": { kind: "lunge", equipment: "bodyweight", unilateral: true, variant: "reverse-lunge" },
  "reverse-pec-deck": { kind: "fly", equipment: "machine", angle: "flat", variant: "reverse-pec-deck" },
  "reverse-grip-pushdown": { kind: "triceps", equipment: "cable", grip: "supinated", cablePath: "straight", variant: "reverse-grip-pushdown" },
  "romanian-deadlift": { kind: "hinge", equipment: "barbell", stance: "normal", variant: "romanian-deadlift" },
  "rope-pushdown": { kind: "triceps", equipment: "cable", cablePath: "straight", variant: "rope-pushdown" },
  "rowing-machine": { kind: "cardio", equipment: "cardio", variant: "rowing-machine" },
  "russian-twist": { kind: "core", equipment: "bodyweight", variant: "russian-twist" },
  "seated-barbell-overhead-press": { kind: "overhead_press", equipment: "barbell", variant: "seated-barbell-overhead-press" },
  "seated-cable-row": { kind: "row", equipment: "cable", grip: "pronated", cablePath: "straight", variant: "seated-cable-row" },
  "seated-dumbbell-shoulder-press": { kind: "overhead_press", equipment: "dumbbell", variant: "seated-dumbbell-shoulder-press" },
  "seated-leg-curl": { kind: "machine_other", equipment: "machine", grip: "supinated", variant: "seated-leg-curl" },
  "side-plank": { kind: "core", equipment: "bodyweight", variant: "side-plank" },
  "single-arm-cable-row": { kind: "row", equipment: "cable", unilateral: true, grip: "pronated", cablePath: "straight", variant: "single-arm-cable-row" },
  "single-arm-dumbbell-bench-press": { kind: "bench", equipment: "dumbbell", angle: "flat", unilateral: true, variant: "single-arm-dumbbell-bench-press" },
  "single-arm-dumbbell-row": { kind: "row", equipment: "dumbbell", unilateral: true, grip: "pronated", variant: "single-arm-dumbbell-row" },
  "single-arm-lat-pulldown": { kind: "pulldown", equipment: "cable", unilateral: true, grip: "pronated", cablePath: "straight", variant: "single-arm-lat-pulldown" },
  "single-leg-hip-thrust": { kind: "hip_thrust", equipment: "barbell", unilateral: true, variant: "single-leg-hip-thrust" },
  "single-leg-press": { kind: "squat", equipment: "machine", stance: "normal", unilateral: true, variant: "single-leg-press" },
  "single-leg-romanian-deadlift": { kind: "hinge", equipment: "dumbbell", unilateral: true, stance: "normal", variant: "single-leg-romanian-deadlift" },
  "skullcrusher": { kind: "triceps", equipment: "barbell", variant: "skullcrusher" },
  "sled-push": { kind: "cardio", equipment: "cardio", variant: "sled-push" },
  "smith-machine-bench-press": { kind: "bench", equipment: "machine", angle: "flat", variant: "smith-machine-bench-press" },
  "smith-machine-shoulder-press": { kind: "overhead_press", equipment: "machine", variant: "smith-machine-shoulder-press" },
  "smith-machine-squat": { kind: "squat", equipment: "machine", stance: "normal", variant: "smith-machine-squat" },
  "snatch-grip-deadlift": { kind: "hinge", equipment: "barbell", stance: "normal", variant: "snatch-grip-deadlift" },
  "stair-climber": { kind: "cardio", equipment: "cardio", variant: "stair-climber" },
  "stationary-bike": { kind: "cardio", equipment: "cardio", variant: "stationary-bike" },
  "step-up": { kind: "squat", equipment: "bodyweight", stance: "normal", variant: "step-up" },
  "stiff-leg-deadlift": { kind: "hinge", equipment: "barbell", stance: "normal", variant: "stiff-leg-deadlift" },
  "straight-arm-pulldown": { kind: "pulldown", equipment: "cable", grip: "pronated", cablePath: "straight", variant: "straight-arm-pulldown" },
  "t-bar-row": { kind: "row", equipment: "machine", grip: "pronated", variant: "t-bar-row" },
  "tempo-back-squat": { kind: "squat", equipment: "barbell", stance: "normal", variant: "tempo-back-squat" },
  "tempo-barbell-bench-press": { kind: "bench", equipment: "barbell", angle: "flat", variant: "tempo-barbell-bench-press" },
  "tempo-deadlift": { kind: "hinge", equipment: "barbell", stance: "normal", variant: "tempo-deadlift" },
  "treadmill-run": { kind: "cardio", equipment: "cardio", variant: "treadmill-run" },
  "triceps-pushdown": { kind: "triceps", equipment: "cable", cablePath: "straight", variant: "triceps-pushdown" },
  "upright-row": { kind: "row", equipment: "barbell", grip: "pronated", variant: "upright-row" },
  "walking-lunge": { kind: "lunge", equipment: "bodyweight", unilateral: true, variant: "walking-lunge" },
  "weighted-plank": { kind: "core", equipment: "bodyweight", variant: "weighted-plank" },
  "weighted-pull-up": { kind: "pulldown", equipment: "bodyweight", grip: "pronated", variant: "weighted-pull-up" },
  "weighted-push-up": { kind: "bench", equipment: "bodyweight", angle: "flat", variant: "weighted-push-up" },
  "wide-grip-lat-pulldown": { kind: "pulldown", equipment: "cable", grip: "wide", cablePath: "straight", stance: "wide", variant: "wide-grip-lat-pulldown" },
  "yates-row": { kind: "row", equipment: "barbell", grip: "pronated", variant: "yates-row" },
};
