import type { ExerciseInfoSheetExercise } from "@/components/ExerciseInfoSheet";
import type { SessionExerciseFocusItem } from "@/components/SessionExerciseFocus";
import type { ExerciseBrowserRow } from "@/lib/exercises-browser";
import type { DayDetailExerciseListItem } from "@/components/routines/day-detail/DayDetailExerciseList";

export const stretchPreviewExercise: ExerciseInfoSheetExercise = {
  id: "preview-stretch",
  exercise_id: "preview-stretch",
  name: "Stretch",
  primary_muscle: "recovery",
  equipment: "bodyweight",
  movement_pattern: "mobility",
  image_howto_path: "/exercises/stretch-hub-hero.svg",
  how_to_short: "Use this hub as a quick mobility reference. Pick the area that feels restricted, breathe steadily, and hold only the range you can own cleanly.",
  image_icon_path: null,
  slug: "stretch",
};

export const stretchPreviewSessionExercise: SessionExerciseFocusItem = {
  id: "preview-session-stretch",
  exerciseId: "preview-stretch",
  name: "Stretch",
  isSkipped: false,
  defaultUnit: null,
  isCardio: false,
  measurementType: "time",
  primary_muscle: "recovery",
  equipment: "bodyweight",
  movement_pattern: "mobility",
  useIntervalLanguage: false,
  initialEnabledMetrics: {
    reps: false,
    weight: false,
    time: false,
    distance: false,
    calories: false,
  },
  routineDayExerciseId: "preview-routine-stretch",
  planTargetsHash: null,
  goalLabel: "Reference-only mobility block",
  initialSets: [],
  loggedSetCount: 0,
  targetSetsMin: null,
  targetSetsMax: null,
  image_path: "/exercises/stretch-hub-hero.svg",
  image_icon_path: null,
  image_howto_path: "/exercises/stretch-hub-hero.svg",
  slug: "stretch",
};

export const stretchPreviewPickerExercises = [
  {
    id: "preview-picker-stretch",
    exercise_id: "preview-stretch",
    name: "Stretch",
    user_id: null,
    is_global: true,
    primary_muscle: "recovery",
    equipment: "bodyweight",
    movement_pattern: "mobility",
    measurement_type: "time" as const,
    default_unit: "s",
    calories_estimation_method: null,
    image_howto_path: "/exercises/stretch-hub-hero.svg",
    how_to_short: "Reference-only mobility hub",
    image_icon_path: null,
    slug: "stretch",
  },
  {
    id: "preview-picker-squat",
    exercise_id: "preview-squat",
    name: "Back Squat",
    user_id: null,
    is_global: true,
    primary_muscle: "quads",
    equipment: "barbell",
    movement_pattern: "squat",
    measurement_type: "reps" as const,
    default_unit: null,
    calories_estimation_method: null,
    image_howto_path: "/exercises/placeholders/howto.svg",
    how_to_short: "Brace, sit between the hips, and drive up through the full foot.",
    image_icon_path: null,
    slug: "back-squat",
  },
];

export const stretchPreviewHistoryRow: ExerciseBrowserRow = {
  exerciseId: "preview-stretch",
  name: "Stretch",
  slug: "stretch",
  image_path: "/exercises/stretch-hub-hero.svg",
  image_icon_path: null,
  image_howto_path: "/exercises/stretch-hub-hero.svg",
  how_to_short: "Reference-only mobility hub",
  primary_muscle: "recovery",
  equipment: "bodyweight",
  movement_pattern: "mobility",
  last_performed_at: null,
  last_weight: null,
  last_reps: null,
  last_unit: null,
  pr_weight: null,
  pr_reps: null,
  pr_est_1rm: null,
  actual_pr_weight: null,
  actual_pr_reps: null,
  actual_pr_at: null,
  kind: "strength",
  lastSummary: null,
  bestSummary: null,
  prLabel: "",
  prCount: 0,
  sessionCount: 0,
  deltaFromBest: null,
  tagsSummary: null,
};

export const stretchPreviewTodayRows = [
  {
    id: "preview-today-stretch",
    exerciseId: "preview-stretch",
    name: "Stretch",
    targets: null,
    image_path: "/exercises/stretch-hub-hero.svg",
    image_icon_path: null,
    image_howto_path: "/exercises/stretch-hub-hero.svg",
    slug: "stretch",
    loggedSetCount: 0,
    isSkipped: false,
    targetSetsMin: null,
    targetSetsMax: null,
    primary_muscle: "recovery",
    equipment: "bodyweight",
    movement_pattern: "mobility",
    measurement_type: "time" as const,
    isCardio: false,
    kind: "strength",
    type: null,
    tags: null,
    categories: null,
  },
];

export const stretchPreviewDayPlanItems: DayDetailExerciseListItem[] = [
  {
    id: "preview-day-stretch",
    name: "Stretch",
    summary: null,
    orderNumber: 1,
    measurementType: "time",
    primary_muscle: "recovery",
    equipment: "bodyweight",
    movement_pattern: "mobility",
    isCardio: false,
    kind: "strength",
    type: null,
    tags: null,
    categories: null,
    slug: "stretch",
    image_path: "/exercises/stretch-hub-hero.svg",
    image_icon_path: null,
    image_howto_path: "/exercises/stretch-hub-hero.svg",
  },
];
