import tokensPack from "../../../../truth-pack/fitness/design-system/tokens.v1.json";
import primitivesPack from "../../../../truth-pack/fitness/design-system/primitives.v1.json";

export const fitnessDesignTokens = tokensPack.tokenGroups;
export const fitnessDesignPrimitiveContracts = primitivesPack.primitiveContracts;

const toArbitraryValue = (value: string) => value.replace(/\s+/g, "_");
const toCompactValue = (value: string) => value.replace(/\s+/g, "");
const withOpacity = (value: string, opacity: string) => {
  const compactValue = toCompactValue(value);
  return compactValue.endsWith(")") ? `${compactValue.slice(0, -1)}/${opacity})` : compactValue;
};

export const fitnessDesignPrimitiveClassNames = {
  header: {
    horizontalPadding: `px-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] sm:px-[${toArbitraryValue(fitnessDesignTokens.spacing["5"])}]`,
    primaryRowGap: `gap-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}]`,
    actionRailGap: `gap-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}]`,
    trailingSlot: `min-h-[${toArbitraryValue(fitnessDesignTokens.spacing["12"])}] min-w-[${toArbitraryValue(fitnessDesignTokens.spacing["12"])}]`,
    titleClassName: fitnessDesignTokens.typography.title,
    titleToSecondaryGap: `mt-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}]`,
    secondaryBlockGap: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["0.5"])}]`,
    contentBottomGap: `pb-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}]`,
    eyebrowClassName: fitnessDesignTokens.typography.eyebrow,
    subtitleClassName: `${fitnessDesignTokens.typography.subtitle} text-[${withOpacity(fitnessDesignTokens.colors.text.secondary, "0.98")}]`,
    metaClassName: `${fitnessDesignTokens.typography.subtitle} text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.98")}]`,
    titleTextClassName: `text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}]`,
  },
  headerFamily: {
    panelClassName: `space-y-0 rounded-[${fitnessDesignTokens.radii.xl}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] shadow-[${toArbitraryValue(fitnessDesignTokens.shadows.glassRaised)}]`,
    headerClassName: "",
    titleClassName: fitnessDesignTokens.typography.title,
    actionClassName: "",
    actionButtonClassName: `h-[${toArbitraryValue(fitnessDesignTokens.spacing["10"])}] w-[${toArbitraryValue(fitnessDesignTokens.spacing["10"])}] rounded-[${fitnessDesignTokens.radii.pill}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.background.panel, "0.58")}] px-0 shadow-[${toArbitraryValue(fitnessDesignTokens.shadows.glassBase)}] hover:border-[${toCompactValue(fitnessDesignTokens.borders.strong)}] hover:bg-[${withOpacity(fitnessDesignTokens.colors.surface["1"], "0.78")}]`,
    metaClassName: `px-[${toArbitraryValue(fitnessDesignTokens.spacing["5"])}] pb-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}]`,
    dividerClassName: `px-[${toArbitraryValue(fitnessDesignTokens.spacing["5"])}] pb-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}]`,
  },
  card: {
    panelBase: `relative isolate overflow-hidden rounded-[${fitnessDesignTokens.radii.lg}] border border-[${toCompactValue(fitnessDesignTokens.borders.strong)}] bg-[${toCompactValue(fitnessDesignTokens.colors.background.card)}] p-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] shadow-[${toArbitraryValue(fitnessDesignTokens.shadows.glassBase)}] backdrop-blur-[10px]`,
    panelMuted: `rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.72")}] p-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}]`,
    rowBase: `rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.strong)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.84")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["3.5"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}]`,
    rowInteractive: "transition-[transform,filter] duration-75 ease-out active:scale-[0.992] active:brightness-[1.02]",
    rowAccent: `border-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.34")}] bg-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.1")}]`,
    rowDefault: `border-[${toCompactValue(fitnessDesignTokens.borders.strong)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.84")}] hover:border-[rgb(var(--border-strong)/0.28)] hover:bg-[${withOpacity(fitnessDesignTokens.colors.surface["3"], "0.94")}]`,
    exerciseLogHeaderPanelClassName: `overflow-hidden border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.background.panel, "0.74")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] pb-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] pt-[${toArbitraryValue(fitnessDesignTokens.spacing["6"])}] backdrop-blur-[10px]`,
    exerciseLogSectionPanelClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] rounded-[${fitnessDesignTokens.radii.lg}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.48")}] p-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}]`,
    exerciseLogInsetPanelClassName: `rounded-[${fitnessDesignTokens.radii.lg}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.42")}] p-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}]`,
    exerciseLogRowClassName: `flex items-stretch justify-between gap-0 overflow-hidden rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.34")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}] shadow-[${toArbitraryValue(fitnessDesignTokens.shadows.glassBase)}]`,
    exerciseLogStickyShellClassName: `sticky bottom-0 z-30 mt-auto -mx-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] pb-[calc(var(--app-safe-bottom)+2px)] pt-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}] [padding-bottom:max(calc(env(safe-area-inset-bottom)+2px),calc(var(--app-safe-bottom)+2px))] bg-[linear-gradient(180deg,rgba(var(--surface-rgb),0)_0%,rgba(var(--surface-rgb),0.8)_38%,rgba(var(--surface-rgb),0.96)_100%)]`,
    exerciseLogMetricClassName: `min-w-0 rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.42")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}]`,
    exerciseLogMetricWarningClassName: `border-[${withOpacity(fitnessDesignTokens.colors.status.warning, "0.22")}] bg-[${withOpacity(fitnessDesignTokens.colors.status.warning, "0.1")}]`,
    exerciseLogMetricLabelClassName: `text-[10px] font-semibold uppercase tracking-[0.16em] text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.98")}]`,
    exerciseLogMetricValueClassName: `mt-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] text-sm font-medium leading-[1.3] text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}]`,
    measurementFieldClassName: `min-h-[5.15rem] rounded-[${fitnessDesignTokens.radii.md}] border px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] transition-colors`,
    measurementFieldCompactClassName: `border-[${toCompactValue(fitnessDesignTokens.borders.strong)}] bg-[${withOpacity(fitnessDesignTokens.colors.background.app, "0.26")}]`,
    measurementFieldStandardClassName: `border-[${toCompactValue(fitnessDesignTokens.borders.strong)}] bg-[${withOpacity(fitnessDesignTokens.colors.background.app, "0.28")}]`,
    measurementFieldWideClassName: `border-[${toCompactValue(fitnessDesignTokens.borders.strong)}] bg-[${withOpacity(fitnessDesignTokens.colors.background.app, "0.34")}]`,
    measurementInputClassName: `input-no-spinner mt-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}] h-11 w-full rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.focus)}] bg-[${withOpacity(fitnessDesignTokens.colors.background.app, "0.48")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] text-[15px] font-semibold tabular-nums text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}] placeholder:text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.5")}] focus-visible:border-[${toCompactValue(fitnessDesignTokens.borders.focus)}] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[${toCompactValue(fitnessDesignTokens.borders.focus)}]`,
    measurementValidationClassName: `rounded-[${fitnessDesignTokens.radii.md}] border border-[${withOpacity(fitnessDesignTokens.colors.status.warning, "0.28")}] bg-[${withOpacity(fitnessDesignTokens.colors.status.warning, "0.12")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}] text-xs text-[${withOpacity(fitnessDesignTokens.colors.status.warning, "0.95")}]`,
    workoutCardDisclosureShellClassName: `overflow-hidden rounded-[${fitnessDesignTokens.radii.lg}]`,
    workoutCardExpandedPanelClassName: `border-t border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["3.5"])}] pb-[${toArbitraryValue(fitnessDesignTokens.spacing["3.5"])}] pt-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}] sm:px-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}]`,
    workoutCardGoalRowCompactClassName: `rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.52")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}]`,
    workoutCardGoalRowDetailedClassName: `rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.56")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["1.5"])}]`,
    workoutMetricChromeClassName: `min-w-0 rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.54")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}]`,
    workoutMetricCompactClassName: `px-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["1.5"])}]`,
    workoutMetricStripClassName: `min-w-[8.35rem] basis-[calc(50%-0.375rem)] flex-1 px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}]`,
    workoutMetricValueCompactClassName: `text-[13px]`,
    settingsRowClassName: `rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.2")}]`,
    settingsExpandedPanelClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.background.app, "0.12")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}]`,
    settingsTextareaClassName: `min-h-[16rem] w-full rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.92")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] font-mono text-[13px] leading-5 text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}] placeholder:text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.92")}] focus-visible:border-[${toCompactValue(fitnessDesignTokens.borders.focus)}] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[${toCompactValue(fitnessDesignTokens.borders.focus)}]`,
    detailStateCardClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["1.5"])}] rounded-[${fitnessDesignTokens.radii.md}] border px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}]`,
    detailMediaCardClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.54")}] p-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}]`,
    detailMediaFrameClassName: `flex aspect-[4/3] w-full items-center justify-center overflow-hidden rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["1"], "0.52")}] p-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}]`,
    detailHistoryRowClassName: `min-w-0 rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["1"], "0.52")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}]`,
    stickyBar: `rounded-[${fitnessDesignTokens.radii.lg}] border border-[${toCompactValue(fitnessDesignTokens.borders.strong)}] bg-[${withOpacity(fitnessDesignTokens.colors.background.panel, "0.94")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}] shadow-[${toArbitraryValue(fitnessDesignTokens.shadows.glassRaised)}] backdrop-blur-[10px]`,
  },
  badge: {
    baseClassName: `inline-flex shrink-0 items-center justify-center whitespace-nowrap rounded-[${fitnessDesignTokens.radii.pill}] border px-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] ${fitnessDesignTokens.typography.badge}`,
    todayClassName: `border-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.36")}] bg-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.14")}] text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}]`,
    defaultClassName: `border-[${toCompactValue(fitnessDesignTokens.borders.strong)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["3"], "0.92")}] text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.9")}]`,
    successClassName: `border-[${withOpacity(fitnessDesignTokens.colors.status.success, "0.34")}] bg-[${withOpacity(fitnessDesignTokens.colors.status.success, "0.14")}] text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}]`,
    warningClassName: `border-[${withOpacity(fitnessDesignTokens.colors.status.warning, "0.34")}] bg-[${withOpacity(fitnessDesignTokens.colors.status.warning, "0.14")}] text-[rgb(255_242_220)]`,
    destructiveClassName: `border-[${withOpacity(fitnessDesignTokens.colors.status.danger, "0.34")}] bg-[${withOpacity(fitnessDesignTokens.colors.status.danger, "0.12")}] text-[rgb(255_228_233)]`,
    summaryMutedClassName: `border-[${toCompactValue(fitnessDesignTokens.borders.strong)}] bg-[${withOpacity(fitnessDesignTokens.colors.background.app, "0.24")}] text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.98")}]`,
    workoutChipCompactClassName: `normal-case tracking-[0.01em] px-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] text-[9px]`,
    workoutChipDetailedClassName: `normal-case tracking-[0.01em] px-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] text-[10px]`,
  },
  sectionLayout: {
    sectionHeaderClassName: `flex items-start justify-between gap-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}]`,
    sectionLabelClassName: `${fitnessDesignTokens.typography.sectionLabel} text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.98")}]`,
    sectionShellStandardClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] p-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}]`,
    sectionShellDenseClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}]`,
    sectionShellSpaciousClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] p-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}]`,
    sectionBodyStandardClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}]`,
    sectionBodyDenseClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}]`,
    measurementHeaderMetaClassName: `text-[11px] text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.92")}]`,
    measurementInlineSummaryClassName: `${fitnessDesignTokens.typography.body} text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.88")}]`,
    workoutCardContentCompactClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}]`,
    workoutCardContentDetailedClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}]`,
    workoutCardSummaryCompactClassName: `text-sm leading-snug text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.86")}]`,
    workoutCardSummaryDetailedClassName: `text-[0.95rem] leading-[1.45] text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.9")}]`,
    workoutCardDetailCompactClassName: `text-[11px] leading-[1.45] text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.94")}]`,
    workoutCardDetailDetailedClassName: `text-xs leading-[1.5] text-[${withOpacity(fitnessDesignTokens.colors.text.secondary, "0.9")}]`,
    workoutCardDetailsCompactClassName: `min-w-0 space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}]`,
    workoutCardDetailsDetailedClassName: `min-w-0 space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["1.5"])}]`,
    workoutCardChipRowCompactClassName: `flex flex-wrap gap-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] pt-0`,
    workoutCardChipRowDetailedClassName: `flex flex-wrap gap-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] pt-[${toArbitraryValue(fitnessDesignTokens.spacing["0.5"])}]`,
    workoutMetricLabelClassName: `min-w-0 text-[10px] font-semibold uppercase tracking-[0.14em] text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.9")}]`,
    workoutMetricValueClassName: `mt-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] min-w-0 text-sm font-semibold leading-[1.16] text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}] [text-wrap:pretty]`,
    workoutMetricMetaClassName: `mt-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] min-w-0 text-[11px] leading-[1.35] text-[${withOpacity(fitnessDesignTokens.colors.text.secondary, "0.86")}] [text-wrap:pretty]`,
    workoutMetricStripMetaClassName: `mt-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] min-w-0 text-[10px] leading-[1.3] text-[${withOpacity(fitnessDesignTokens.colors.text.secondary, "0.82")}] [text-wrap:pretty]`,
    workoutMetricGridClassName: `grid grid-cols-2 gap-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}]`,
    settingsCardHeaderClassName: `-mx-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] -mt-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] pb-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] sm:-mx-[${toArbitraryValue(fitnessDesignTokens.spacing["5"])}]`,
    settingsSectionTitleClassName: `text-[1.3125rem] font-semibold leading-[1.04] tracking-[-0.03em] text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}]`,
    settingsFieldStackClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}]`,
    settingsBlockStackClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}]`,
    settingsBodyTextClassName: `text-sm leading-5 text-[${withOpacity(fitnessDesignTokens.colors.text.secondary, "0.92")}]`,
    settingsDividerClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] border-t border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] pt-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}]`,
    detailSectionClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] p-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}]`,
    detailSectionTitleClassName: `text-[1.3125rem] font-semibold leading-[1.04] tracking-[-0.03em] text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}]`,
    detailMetaRowClassName: `flex flex-wrap gap-[${toArbitraryValue(fitnessDesignTokens.spacing["1.5"])}]`,
    detailMetaChipClassName: `min-w-0 rounded-[${fitnessDesignTokens.radii.pill}] border px-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] text-[11px] font-medium leading-none`,
    detailMetaChipDefaultClassName: `border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["3"], "0.92")}] text-[${withOpacity(fitnessDesignTokens.colors.text.secondary, "0.96")}]`,
    detailMetaChipEmphasizedClassName: `border-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.34")}] bg-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.14")}] text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}]`,
    detailMetaChipLabelClassName: `text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.94")}]`,
    detailMetaChipValueClassName: `ml-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}]`,
    detailBodyTextClassName: `text-sm leading-6`,
    detailBodyMutedTextClassName: `text-sm leading-6 text-[${withOpacity(fitnessDesignTokens.colors.text.secondary, "0.84")}]`,
    detailMetaTextClassName: `text-xs leading-5`,
  },
} as const;
