import tokensPack from "../../../../truth-pack/fitness/design-system/tokens.v1.json";
import primitivesPack from "../../../../truth-pack/fitness/design-system/primitives.v1.json";

export const fitnessDesignTokens = tokensPack.tokenGroups;
export const fitnessDesignPrimitiveContracts = primitivesPack.primitiveContracts;

const toArbitraryValue = (value: string | null | undefined, fallback = "0") => (value ?? fallback).replace(/\s+/g, "_");
const toCompactValue = (value: string | null | undefined, fallback = "0") => (value ?? fallback).replace(/\s+/g, "");
const withOpacity = (value: string | null | undefined, opacity: string) => {
  const compactValue = toCompactValue(value, "transparent");
  return compactValue.endsWith(")") ? `${compactValue.slice(0, -1)}/${opacity})` : compactValue;
};

export const fitnessDesignPrimitiveClassNames = {
  header: {
    horizontalPadding: `px-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] sm:px-[${toArbitraryValue(fitnessDesignTokens.spacing["5"])}]`,
    primaryRowGap: `gap-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}]`,
    actionRailGap: `gap-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}]`,
    trailingSlot: `min-h-[${toArbitraryValue(fitnessDesignTokens.spacing["12"])}] min-w-[${toArbitraryValue(fitnessDesignTokens.spacing["12"])}]`,
    titleClassName: fitnessDesignTokens.typography.title,
    titleToSecondaryGap: `mt-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}]`,
    secondaryBlockGap: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["0.5"])}]`,
    contentBottomGap: `pb-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}]`,
    eyebrowClassName: fitnessDesignTokens.typography.eyebrow,
    subtitleClassName: `${fitnessDesignTokens.typography.subtitle} text-[${withOpacity(fitnessDesignTokens.colors.text.secondary, "0.98")}]`,
    metaClassName: `${fitnessDesignTokens.typography.subtitle} text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.98")}]`,
    titleTextClassName: `text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}]`,
  },
  headerFamily: {
    panelClassName: `space-y-0 rounded-[${fitnessDesignTokens.radii.xl}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] shadow-[${toArbitraryValue(fitnessDesignTokens.shadows.glassRaised)}]`,
    headerClassName: "",
    titleClassName: fitnessDesignTokens.typography.title,
    actionClassName: "",
    actionButtonClassName: `h-[2.35rem] w-[2.35rem] rounded-[${fitnessDesignTokens.radii.pill}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.background.panel, "0.48")}] px-0 shadow-[0_12px_24px_rgba(0,0,0,0.16)] hover:border-[${toCompactValue(fitnessDesignTokens.borders.strong)}] hover:bg-[${withOpacity(fitnessDesignTokens.colors.surface["1"], "0.72")}]`,
    metaClassName: `px-[${toArbitraryValue(fitnessDesignTokens.spacing["5"])}] pb-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}]`,
    dividerClassName: `px-[${toArbitraryValue(fitnessDesignTokens.spacing["5"])}] pb-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}]`,
  },
  card: {
    panelBase: `relative isolate overflow-hidden rounded-[${fitnessDesignTokens.radii.lg}] border border-[${toCompactValue(fitnessDesignTokens.borders.strong)}] bg-[${toCompactValue(fitnessDesignTokens.colors.background.card)}] p-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] shadow-[${toArbitraryValue(fitnessDesignTokens.shadows.glassBase)}] backdrop-blur-[10px]`,
    panelMuted: `rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.72")}] p-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}]`,
    rowBase: `rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.strong)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.84")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["3.5"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}]`,
    rowInteractive: "transition-[transform,filter] duration-75 ease-out active:scale-[0.992] active:brightness-[1.02]",
    rowAccent: `border-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.34")}] bg-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.1")}]`,
    rowDefault: `border-[${toCompactValue(fitnessDesignTokens.borders.strong)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.84")}] hover:border-[rgb(var(--border-strong)/0.28)] hover:bg-[${withOpacity(fitnessDesignTokens.colors.surface["3"], "0.94")}]`,
    exerciseLogHeaderPanelClassName: `overflow-hidden border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.background.panel, "0.74")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] pb-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] pt-[${toArbitraryValue(fitnessDesignTokens.spacing["6"])}] backdrop-blur-[10px]`,
    exerciseLogSectionPanelClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] rounded-[${fitnessDesignTokens.radii.lg}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.48")}] p-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}]`,
    exerciseLogInsetPanelClassName: `rounded-[${fitnessDesignTokens.radii.lg}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.42")}] p-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}]`,
    exerciseLogRowClassName: `flex items-stretch justify-between gap-0 overflow-hidden rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.34")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}] shadow-[${toArbitraryValue(fitnessDesignTokens.shadows.glassBase)}]`,
    exerciseLogStickyShellClassName: `sticky bottom-0 z-30 mt-auto -mx-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] pb-[calc(var(--app-safe-bottom)+2px)] pt-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}] [padding-bottom:max(calc(env(safe-area-inset-bottom)+2px),calc(var(--app-safe-bottom)+2px))] bg-[linear-gradient(180deg,rgba(var(--surface-rgb),0)_0%,rgba(var(--surface-rgb),0.8)_38%,rgba(var(--surface-rgb),0.96)_100%)]`,
    exerciseLogMetricClassName: `min-w-0 rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.42")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}]`,
    exerciseLogMetricWarningClassName: `border-[${withOpacity(fitnessDesignTokens.colors.status.warning, "0.22")}] bg-[${withOpacity(fitnessDesignTokens.colors.status.warning, "0.1")}]`,
    exerciseLogMetricLabelClassName: `text-[10px] font-semibold uppercase tracking-[0.16em] text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.98")}]`,
    exerciseLogMetricValueClassName: `mt-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] text-sm font-medium leading-[1.3] text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}]`,
    measurementFieldClassName: `min-h-[5.15rem] rounded-[${fitnessDesignTokens.radii.md}] border px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] transition-colors`,
    measurementFieldCompactClassName: `border-[${toCompactValue(fitnessDesignTokens.borders.strong)}] bg-[${withOpacity(fitnessDesignTokens.colors.background.app, "0.26")}]`,
    measurementFieldStandardClassName: `border-[${toCompactValue(fitnessDesignTokens.borders.strong)}] bg-[${withOpacity(fitnessDesignTokens.colors.background.app, "0.28")}]`,
    measurementFieldWideClassName: `border-[${toCompactValue(fitnessDesignTokens.borders.strong)}] bg-[${withOpacity(fitnessDesignTokens.colors.background.app, "0.34")}]`,
    measurementInputClassName: `input-no-spinner mt-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}] h-11 w-full rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.focus)}] bg-[${withOpacity(fitnessDesignTokens.colors.background.app, "0.48")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] text-[15px] font-semibold tabular-nums text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}] placeholder:text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.5")}] focus-visible:border-[${toCompactValue(fitnessDesignTokens.borders.focus)}] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[${toCompactValue(fitnessDesignTokens.borders.focus)}]`,
    measurementValidationClassName: `rounded-[${fitnessDesignTokens.radii.md}] border border-[${withOpacity(fitnessDesignTokens.colors.status.warning, "0.28")}] bg-[${withOpacity(fitnessDesignTokens.colors.status.warning, "0.12")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}] text-xs text-[${withOpacity(fitnessDesignTokens.colors.status.warning, "0.95")}]`,
    workoutCardDisclosureShellClassName: `overflow-hidden rounded-[${fitnessDesignTokens.radii.lg}]`,
    workoutCardExpandedPanelClassName: `border-t border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["3.5"])}] pb-[${toArbitraryValue(fitnessDesignTokens.spacing["3.5"])}] pt-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}] sm:px-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}]`,
    workoutCardGoalRowCompactClassName: `rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.52")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}]`,
    workoutCardGoalRowDetailedClassName: `rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.56")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["1.5"])}]`,
    workoutMetricChromeClassName: `min-w-0 rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.54")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}]`,
    workoutMetricCompactClassName: `px-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["1.5"])}]`,
    workoutMetricStripClassName: `min-w-[8.35rem] basis-[calc(50%-0.375rem)] flex-1 px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}]`,
    workoutMetricValueCompactClassName: `text-[13px]`,
    exercisePickerPanelClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}] rounded-none border-0 bg-transparent p-0 shadow-none md:rounded-[${fitnessDesignTokens.radii.lg}] md:border md:border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] md:bg-[linear-gradient(180deg,${withOpacity(fitnessDesignTokens.colors.surface["3"], "0.08")},${withOpacity(fitnessDesignTokens.colors.surface["1"], "0.04")})] md:p-[${toArbitraryValue(fitnessDesignTokens.spacing["3.5"])}] md:shadow-[0_16px_34px_-20px_rgba(0,0,0,0.92)] lg:p-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}]`,
    exercisePickerGoalPanelClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}] rounded-[${fitnessDesignTokens.radii.lg}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.46")}] p-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}]`,
    exercisePickerFilterToggleClassName: `min-h-[${toArbitraryValue(fitnessDesignTokens.spacing["10"])}] w-full justify-between rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.background.app, "0.18")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}] text-sm font-medium [-webkit-tap-highlight-color:transparent]`,
    exercisePickerFilterCountBadgeClassName: `inline-flex min-h-[${toArbitraryValue(fitnessDesignTokens.spacing["5"])}] min-w-[${toArbitraryValue(fitnessDesignTokens.spacing["5"])}] items-center justify-center rounded-[${fitnessDesignTokens.radii.pill}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.background.app, "0.45")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["1.5"])}] text-[11px] font-semibold text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.96")}]`,
    exercisePickerFilterPanelClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}] rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.background.app, "0.16")}] p-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}]`,
    exercisePickerFilterClearButtonClassName: `inline-flex min-h-[${toArbitraryValue(fitnessDesignTokens.spacing["6"])}] items-center rounded-[${fitnessDesignTokens.radii.pill}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.background.app, "0.35")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}] text-[11px] font-medium uppercase tracking-[0.1em] text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.96")}] transition-colors hover:text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}]`,
    exercisePickerSearchClearButtonClassName: `absolute right-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}] top-1/2 inline-flex h-6 w-6 -translate-y-1/2 items-center justify-center rounded-[${fitnessDesignTokens.radii.pill}] text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.96")}] transition-colors hover:bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.54")}] hover:text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.25")}]`,
    exercisePickerViewportShellClassName: `overflow-visible rounded-none border-0 bg-transparent p-0 md:relative md:overflow-hidden md:rounded-[${fitnessDesignTokens.radii.lg}] md:border md:border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] md:bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.42")}] md:p-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}]`,
    exercisePickerViewportTrayClassName: `relative max-md:overflow-hidden max-md:rounded-[${fitnessDesignTokens.radii.md}] max-md:border max-md:border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] max-md:bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.2")}] max-md:px-[${toArbitraryValue(fitnessDesignTokens.spacing["1.5"])}] max-md:py-[${toArbitraryValue(fitnessDesignTokens.spacing["1.5"])}]`,
    exercisePickerViewportMobileFadeTopClassName: `pointer-events-none absolute inset-x-[${toArbitraryValue(fitnessDesignTokens.spacing["1.5"])}] top-[${toArbitraryValue(fitnessDesignTokens.spacing["1.5"])}] z-10 h-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] rounded-t-[${fitnessDesignTokens.radii.md}] bg-gradient-to-b from-[${withOpacity(fitnessDesignTokens.colors.surface["1"], "0.74")}] via-[${withOpacity(fitnessDesignTokens.colors.surface["1"], "0.22")}] to-transparent md:hidden`,
    exercisePickerViewportMobileFadeBottomClassName: `pointer-events-none absolute inset-x-[${toArbitraryValue(fitnessDesignTokens.spacing["1.5"])}] bottom-[${toArbitraryValue(fitnessDesignTokens.spacing["1.5"])}] z-10 h-[${toArbitraryValue(fitnessDesignTokens.spacing["5"])}] rounded-b-[${fitnessDesignTokens.radii.md}] bg-gradient-to-t from-[${withOpacity(fitnessDesignTokens.colors.surface["1"], "0.82")}] via-[${withOpacity(fitnessDesignTokens.colors.surface["1"], "0.38")}] to-transparent md:hidden`,
    exercisePickerViewportDesktopFadeTopClassName: `pointer-events-none absolute inset-x-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}] top-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}] z-10 hidden h-[${toArbitraryValue(fitnessDesignTokens.spacing["8"])}] rounded-t-[${fitnessDesignTokens.radii.md}] bg-gradient-to-b from-[${withOpacity(fitnessDesignTokens.colors.surface["1"], "0.82")}] via-[${withOpacity(fitnessDesignTokens.colors.surface["1"], "0.3")}] to-transparent md:block`,
    exercisePickerViewportDesktopFadeBottomClassName: `pointer-events-none absolute inset-x-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}] bottom-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}] z-10 hidden h-[${toArbitraryValue(fitnessDesignTokens.spacing["12"])}] rounded-b-[${fitnessDesignTokens.radii.md}] bg-gradient-to-t from-[${withOpacity(fitnessDesignTokens.colors.surface["1"], "0.92")}] via-[${withOpacity(fitnessDesignTokens.colors.surface["1"], "0.55")}] to-transparent md:block`,
    todaySummaryCenteredShellClassName: `flex min-h-[clamp(15rem,40vh,20rem)] flex-col justify-center`,
    todayEmptyStateCardClassName: `rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.72")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] text-center text-sm leading-normal text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.96")}]`,
    todayGlobalErrorCardClassName: `rounded-[${fitnessDesignTokens.radii.md}] border border-[${withOpacity(fitnessDesignTokens.colors.status.danger, "0.24")}] bg-[${withOpacity(fitnessDesignTokens.colors.status.danger, "0.1")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}] text-sm text-[rgb(255_228_233)]`,
    todaySummaryToneBlockingClassName: `border-[${withOpacity(fitnessDesignTokens.colors.status.danger, "0.34")}] bg-[${withOpacity(fitnessDesignTokens.colors.status.danger, "0.12")}] text-[rgb(255_228_233)]`,
    todaySummaryToneCautionClassName: `border-[${withOpacity(fitnessDesignTokens.colors.status.warning, "0.28")}] bg-[${withOpacity(fitnessDesignTokens.colors.status.warning, "0.12")}] text-[rgb(255_242_220)]`,
    settingsRowClassName: `rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.2")}]`,
    settingsExpandedPanelClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.background.app, "0.12")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}]`,
    settingsTextareaClassName: `min-h-[16rem] w-full rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.92")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] font-mono text-[13px] leading-5 text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}] placeholder:text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.92")}] focus-visible:border-[${toCompactValue(fitnessDesignTokens.borders.focus)}] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[${toCompactValue(fitnessDesignTokens.borders.focus)}]`,
    detailStateCardClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["1.5"])}] rounded-[${fitnessDesignTokens.radii.md}] border px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}]`,
    detailMediaCardClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.54")}] p-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}]`,
    detailMediaFrameClassName: `flex aspect-[4/3] w-full items-center justify-center overflow-hidden rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["1"], "0.52")}] p-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}]`,
    detailHistoryRowClassName: `min-w-0 rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["1"], "0.52")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}]`,
    detailLoadingMetricCardClassName: `h-20 animate-pulse rounded-[${fitnessDesignTokens.radii.md}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.54")}]`,
    detailLoadingRowClassName: `h-14 animate-pulse rounded-[${fitnessDesignTokens.radii.md}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.54")}]`,
    routineEditorModeRowClassName: `mb-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] flex items-center justify-between gap-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] rounded-[${fitnessDesignTokens.radii.lg}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.3")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}]`,
    routineEditorToggleRowClassName: `flex w-full items-center justify-between gap-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] rounded-[${fitnessDesignTokens.radii.lg}] border px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}] text-left transition-colors`,
    routineEditorToggleRowEnabledClassName: `border-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.35")}] bg-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.14")}] text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}]`,
    routineEditorToggleRowDefaultClassName: `border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.22")}] text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.96")}] hover:bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.3")}]`,
    routineEditorInlineSectionClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] rounded-[${fitnessDesignTokens.radii.xl}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.58")}] p-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}]`,
    routineEditorInlineBadgeClassName: `rounded-[${fitnessDesignTokens.radii.pill}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.background.panel, "0.92")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}]`,
    routineEditorOrderInputClassName: `h-10 w-full rounded-[${fitnessDesignTokens.radii.lg}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.62")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] text-sm text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}] outline-none transition focus:border-[${toCompactValue(fitnessDesignTokens.borders.focus)}] focus:ring-2 focus:ring-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.22")}]`,
    routineEditorReorderHandleClassName: `inline-flex h-9 w-9 items-center justify-center rounded-[${fitnessDesignTokens.radii.pill}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.background.app, "0.3")}] text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.96")}] transition-colors hover:bg-[${withOpacity(fitnessDesignTokens.colors.background.panel, "0.46")}] touch-none`,
    routineEditorStatusErrorClassName: `rounded-[${fitnessDesignTokens.radii.lg}] border border-[${withOpacity(fitnessDesignTokens.colors.status.danger, "0.34")}] bg-[${withOpacity(fitnessDesignTokens.colors.status.danger, "0.12")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}] text-[${withOpacity(fitnessDesignTokens.colors.status.danger, "0.95")}]`,
    stickyBar: `rounded-[${fitnessDesignTokens.radii.lg}] border border-[${toCompactValue(fitnessDesignTokens.borders.strong)}] bg-[${withOpacity(fitnessDesignTokens.colors.background.panel, "0.94")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}] shadow-[${toArbitraryValue(fitnessDesignTokens.shadows.glassRaised)}] backdrop-blur-[10px]`,
  },
  auth: {
    shellContentClassName: `gap-[${toArbitraryValue(fitnessDesignTokens.spacing["5"])}]`,
    introClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}]`,
    introTitleStackClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}]`,
    introEyebrowClassName: `text-xs font-semibold uppercase tracking-[0.28em] text-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.9")}]`,
    introTitleClassName: `text-[clamp(2.2rem,9vw,2.85rem)] font-semibold tracking-[-0.04em] text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "1")}]`,
    introSubtitleClassName: `max-w-sm text-sm leading-6 text-[${withOpacity(fitnessDesignTokens.colors.text.secondary, "0.96")}]`,
    cardClassName: `glass-surface glass-sheen relative space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["5"])}] rounded-[1.65rem] border border-[${toCompactValue(fitnessDesignTokens.borders.strong)}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["5"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["5"])}] shadow-[0_22px_56px_rgba(0,0,0,0.34)]`,
    interactiveCardClassName: `rounded-[1.85rem] px-[${toArbitraryValue(fitnessDesignTokens.spacing["5"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["5"])}] transition-[transform,opacity,border-color,box-shadow] duration-200 ease-out motion-reduce:transition-none`,
    interactiveCardEmailValidClassName: `border-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.12")}] shadow-[0_24px_70px_rgba(0,0,0,0.38)]`,
    interactiveCardReadyClassName: `border-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.2")}] shadow-[0_30px_90px_rgba(0,0,0,0.42)]`,
    interactiveCardPendingClassName: `-translate-y-1 scale-[0.995] opacity-95`,
    messageClassName: `rounded-[${fitnessDesignTokens.radii.md}] border px-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] text-sm leading-6`,
    messageDefaultClassName: `border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["3"], "0.4")}] text-[${withOpacity(fitnessDesignTokens.colors.text.secondary, "0.98")}]`,
    messageErrorClassName: `border-[${withOpacity(fitnessDesignTokens.colors.status.danger, "0.34")}] bg-[${withOpacity(fitnessDesignTokens.colors.status.danger, "0.12")}] text-[rgb(255_228_233)]`,
    messageSuccessClassName: `border-[${withOpacity(fitnessDesignTokens.colors.status.success, "0.34")}] bg-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.12")}] text-[rgb(222_255_237)]`,
    fieldClassName: `block space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}]`,
    fieldLabelClassName: `text-sm font-medium text-[${withOpacity(fitnessDesignTokens.colors.text.secondary, "0.98")}]`,
    footerClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] border-t border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] pt-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] text-sm text-[${withOpacity(fitnessDesignTokens.colors.text.secondary, "0.96")}]`,
    statusCardClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] text-center`,
    statusSpinnerShellClassName: `mx-auto flex h-11 w-11 items-center justify-center rounded-full border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["3"], "0.42")}] text-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.98")}]`,
    statusTitleClassName: `text-base font-semibold text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "1")}]`,
    statusDescriptionClassName: `text-sm leading-6 text-[${withOpacity(fitnessDesignTokens.colors.text.secondary, "0.96")}]`,
    wordmarkClassName: `text-[11px] font-semibold uppercase tracking-[0.32em] text-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.9")}]`,
    displayNameClassName: `text-[clamp(1.75rem,7vw,2.3rem)] font-semibold tracking-[-0.04em] text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}]`,
    helperTextClassName: `max-w-sm text-sm leading-6 text-[${withOpacity(fitnessDesignTokens.colors.text.secondary, "0.96")}]`,
    helperTextCenteredClassName: `mx-auto max-w-xs text-center`,
    helperTextMutedClassName: `text-xs leading-5 text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.94")}]`,
    subtitleTextClassName: `text-sm leading-6 text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.96")}]`,
    inlineLinkClassName: `font-medium text-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.96")}] underline-offset-4 transition-colors hover:text-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.78")}] hover:underline`,
    utilityActionClassName: `shrink-0 rounded-full border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["1.5"])}] text-[11px] font-semibold uppercase tracking-[0.16em] text-[${withOpacity(fitnessDesignTokens.colors.text.secondary, "0.96")}] transition-colors hover:border-[${toCompactValue(fitnessDesignTokens.borders.strong)}] hover:text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "1")}]`,
    accountPanelClassName: `rounded-[1.15rem] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.background.app, "0.22")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] text-center`,
    accountReadonlyClassName: `rounded-[${fitnessDesignTokens.radii.md}] border border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["3"], "0.22")}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] text-sm text-[${withOpacity(fitnessDesignTokens.colors.text.secondary, "0.96")}]`,
    accountEyebrowClassName: `text-[11px] font-semibold uppercase tracking-[0.16em] text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.88")}]`,
    accountValueClassName: `mt-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] text-sm font-medium text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}]`,
    inputClassName: `h-14 rounded-[1.15rem] border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.background.app, "0.22")}] text-base text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "1")}] placeholder:text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.92")}] transition-[border-color,background-color,box-shadow] duration-200 ease-out motion-reduce:transition-none`,
    inputActiveClassName: `border-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.2")}] bg-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.05")}]`,
    actionButtonClassName: `min-h-[3.35rem] rounded-[1.1rem] text-sm font-semibold tracking-[0.01em] transition-[transform,box-shadow,opacity] duration-200 ease-out motion-reduce:transition-none`,
    actionButtonReadyClassName: `shadow-[0_18px_38px_rgba(16,185,129,0.18)]`,
    actionButtonPendingClassName: `scale-[0.985]`,
    inlineActionClassName: `inline-flex rounded-[${fitnessDesignTokens.radii.md}] bg-[${toCompactValue(fitnessDesignTokens.colors.accent.base)}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}] text-sm text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "1")}] transition-colors hover:bg-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.88")}] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.25")}]`,
    pendingTextClassName: `text-sm leading-6 text-[${withOpacity(fitnessDesignTokens.colors.text.secondary, "0.92")}]`,
  },
  badge: {
    baseClassName: `inline-flex shrink-0 items-center justify-center whitespace-nowrap rounded-[${fitnessDesignTokens.radii.pill}] border px-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] ${fitnessDesignTokens.typography.badge}`,
    todayClassName: `border-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.36")}] bg-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.14")}] text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}]`,
    defaultClassName: `border-[${toCompactValue(fitnessDesignTokens.borders.strong)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["3"], "0.92")}] text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.9")}]`,
    successClassName: `border-[${withOpacity(fitnessDesignTokens.colors.status.success, "0.34")}] bg-[${withOpacity(fitnessDesignTokens.colors.status.success, "0.14")}] text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}]`,
    warningClassName: `border-[${withOpacity(fitnessDesignTokens.colors.status.warning, "0.34")}] bg-[${withOpacity(fitnessDesignTokens.colors.status.warning, "0.14")}] text-[rgb(255_242_220)]`,
    destructiveClassName: `border-[${withOpacity(fitnessDesignTokens.colors.status.danger, "0.34")}] bg-[${withOpacity(fitnessDesignTokens.colors.status.danger, "0.12")}] text-[rgb(255_228_233)]`,
    summaryMutedClassName: `border-[${toCompactValue(fitnessDesignTokens.borders.strong)}] bg-[${withOpacity(fitnessDesignTokens.colors.background.app, "0.24")}] text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.98")}]`,
    workoutChipCompactClassName: `normal-case tracking-[0.01em] px-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] text-[9px]`,
    workoutChipDetailedClassName: `normal-case tracking-[0.01em] px-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] text-[10px]`,
  },
  sectionLayout: {
    sectionHeaderClassName: `flex items-start justify-between gap-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}]`,
    sectionLabelClassName: `${fitnessDesignTokens.typography.sectionLabel} text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.98")}]`,
    sectionShellStandardClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] p-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}]`,
    sectionShellDenseClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}]`,
    sectionShellSpaciousClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] p-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}]`,
    sectionBodyStandardClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}]`,
    sectionBodyDenseClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}]`,
    measurementHeaderMetaClassName: `text-[11px] text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.92")}]`,
    measurementInlineSummaryClassName: `${fitnessDesignTokens.typography.body} text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.88")}]`,
    workoutCardContentCompactClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}]`,
    workoutCardContentDetailedClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}]`,
    workoutCardSummaryCompactClassName: `text-sm leading-snug text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.86")}]`,
    workoutCardSummaryDetailedClassName: `text-[0.95rem] leading-[1.45] text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.9")}]`,
    workoutCardDetailCompactClassName: `text-[11px] leading-[1.45] text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.94")}]`,
    workoutCardDetailDetailedClassName: `text-xs leading-[1.5] text-[${withOpacity(fitnessDesignTokens.colors.text.secondary, "0.9")}]`,
    workoutCardDetailsCompactClassName: `min-w-0 space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}]`,
    workoutCardDetailsDetailedClassName: `min-w-0 space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["1.5"])}]`,
    workoutCardChipRowCompactClassName: `flex flex-wrap gap-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] pt-0`,
    workoutCardChipRowDetailedClassName: `flex flex-wrap gap-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] pt-[${toArbitraryValue(fitnessDesignTokens.spacing["0.5"])}]`,
    workoutMetricLabelClassName: `min-w-0 text-[10px] font-semibold uppercase tracking-[0.14em] text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.9")}]`,
    workoutMetricValueClassName: `mt-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] min-w-0 text-sm font-semibold leading-[1.16] text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}] [text-wrap:pretty]`,
    workoutMetricMetaClassName: `mt-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] min-w-0 text-[11px] leading-[1.35] text-[${withOpacity(fitnessDesignTokens.colors.text.secondary, "0.86")}] [text-wrap:pretty]`,
    workoutMetricStripMetaClassName: `mt-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] min-w-0 text-[10px] leading-[1.3] text-[${withOpacity(fitnessDesignTokens.colors.text.secondary, "0.82")}] [text-wrap:pretty]`,
    workoutMetricGridClassName: `grid grid-cols-2 gap-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}]`,
    dayListClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["1.5"])}] sm:space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}]`,
    todayRouteStackClassName: `flex flex-col gap-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}]`,
    todayOverviewStackClassName: `flex flex-col gap-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}]`,
    todayExerciseListClassName: `flex flex-col gap-[${toArbitraryValue(fitnessDesignTokens.spacing["1.5"])}]`,
    exercisePickerHeaderRowClassName: `flex items-center justify-between gap-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}]`,
    exercisePickerSectionEyebrowClassName: `text-[11px] font-semibold uppercase tracking-[0.16em] text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.96")}]`,
    exercisePickerSectionMetaClassName: `text-xs text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.96")}]`,
    exercisePickerFilterSummaryClassName: `px-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] text-[11px] leading-5 text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.96")}]`,
    exercisePickerFilterGroupLabelClassName: `text-[10px] font-medium uppercase tracking-[0.14em] text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.82")}]`,
    exercisePickerStatsStackClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["0.5"])}] text-xs`,
    exercisePickerStatsTextClassName: `text-xs leading-5 text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.96")}]`,
    exercisePickerStatsEmphasisClassName: `text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.9")}]`,
    exercisePickerRootClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}]`,
    exercisePickerLibrarySectionClassName: `scroll-mb-24 space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] md:px-0`,
    exercisePickerGoalCompactClassName: `scroll-mb-24 max-md:space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["1.5"])}] max-md:px-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] max-md:py-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}]`,
    exercisePickerStatsCompactClassName: `max-md:space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] max-md:text-[11px]`,
    exercisePickerValidationCompactClassName: `max-md:min-h-[${toArbitraryValue(fitnessDesignTokens.spacing["8"])}] max-md:px-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}] max-md:py-[${toArbitraryValue(fitnessDesignTokens.spacing["1.5"])}] max-md:text-[11px] max-md:leading-4`,
    exercisePickerSearchInputClassName: `pr-[${toArbitraryValue(fitnessDesignTokens.spacing["10"])}]`,
    exercisePickerRowSelectPillClassName: `inline-flex min-h-7 min-w-[3.75rem] items-center justify-center rounded-[${fitnessDesignTokens.radii.pill}] border px-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}] text-[11px] font-semibold leading-none`,
    exercisePickerRowSelectPillSelectedClassName: `border-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.28")}] bg-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.12")}] text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}]`,
    exercisePickerRowSelectPillActiveClassName: `border-[${withOpacity(fitnessDesignTokens.colors.status.success, "0.28")}] bg-[${withOpacity(fitnessDesignTokens.colors.status.success, "0.1")}] text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.94")}]`,
    exercisePickerRowSelectPillDefaultClassName: `border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.background.app, "0.32")}] text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.96")}]`,
    settingsCardHeaderClassName: `-mx-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] pb-[${toArbitraryValue(fitnessDesignTokens.spacing["1.5"])}] sm:-mx-[${toArbitraryValue(fitnessDesignTokens.spacing["5"])}]`,
    settingsSectionTitleClassName: `text-[1.3125rem] font-semibold leading-[1.04] tracking-[-0.03em] text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}]`,
    settingsFieldStackClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}]`,
    settingsBlockStackClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}]`,
    settingsBodyTextClassName: `text-sm leading-5 text-[${withOpacity(fitnessDesignTokens.colors.text.secondary, "0.92")}]`,
    settingsDividerClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] border-t border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] pt-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}]`,
    detailSectionClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] p-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}]`,
    detailSectionTitleClassName: `text-[1.3125rem] font-semibold leading-[1.04] tracking-[-0.03em] text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}]`,
    detailMetaRowClassName: `flex flex-wrap gap-[${toArbitraryValue(fitnessDesignTokens.spacing["1.5"])}]`,
    detailMetaChipClassName: `min-w-0 rounded-[${fitnessDesignTokens.radii.pill}] border px-[${toArbitraryValue(fitnessDesignTokens.spacing["2.5"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] text-[11px] font-medium leading-none`,
    detailMetaChipDefaultClassName: `border-[${toCompactValue(fitnessDesignTokens.borders.soft)}] bg-[${withOpacity(fitnessDesignTokens.colors.surface["3"], "0.92")}] text-[${withOpacity(fitnessDesignTokens.colors.text.secondary, "0.96")}]`,
    detailMetaChipEmphasizedClassName: `border-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.34")}] bg-[${withOpacity(fitnessDesignTokens.colors.accent.base, "0.14")}] text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}]`,
    detailMetaChipLabelClassName: `text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.94")}]`,
    detailMetaChipValueClassName: `ml-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}]`,
    detailBodyTextClassName: `text-sm leading-6`,
    detailBodyMutedTextClassName: `text-sm leading-6 text-[${withOpacity(fitnessDesignTokens.colors.text.secondary, "0.84")}]`,
    detailMetaTextClassName: `text-xs leading-5`,
    detailSectionHeaderClassName: `flex items-start justify-between gap-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}]`,
    detailSectionHeaderContentClassName: `min-w-0 space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}]`,
    detailSectionActionClassName: "shrink-0",
    detailSectionDescriptionClassName: "text-sm",
    detailStatsPanelClassName: `min-h-[8.75rem] space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}] text-xs text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.96")}]`,
    detailLoadingMetricsClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}] pt-[${toArbitraryValue(fitnessDesignTokens.spacing["0.5"])}]`,
    detailLoadingMetricsGridClassName: `grid grid-cols-2 gap-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}]`,
    detailLoadingRowsClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}]`,
    detailHistoryListClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}]`,
    detailHistoryMetaClassName: `flex min-w-0 flex-wrap items-start gap-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}]`,
    detailHistoryLabelClassName: `min-w-0 flex-1 text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.88")}]`,
    detailHistoryContextClassName: `min-w-0 max-w-full text-[11px] leading-[1.35] text-[${withOpacity(fitnessDesignTokens.colors.text.secondary, "0.72")}] [text-wrap:pretty]`,
    detailHistoryValueClassName: `mt-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] min-w-0 ${fitnessDesignTokens.typography.body} text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.95")}] [text-wrap:pretty]`,
    routineEditorSectionStackClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}]`,
    routineEditorPageBodyClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] pb-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}]`,
    routineEditorFieldLabelClassName: `block text-sm font-medium text-[${withOpacity(fitnessDesignTokens.colors.text.secondary, "0.98")}]`,
    routineEditorLinkActionClassName: `text-sm font-medium text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.96")}] underline-offset-4 transition-colors hover:text-[${withOpacity(fitnessDesignTokens.colors.text.primary, "0.98")}] hover:underline`,
    routineEditorHelperTextClassName: `px-[${toArbitraryValue(fitnessDesignTokens.spacing["1"])}] text-sm text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.96")}]`,
    routineEditorCompactStackClassName: `space-y-[${toArbitraryValue(fitnessDesignTokens.spacing["3"])}]`,
    routineEditorHeaderSlotClassName: `w-full px-[${toArbitraryValue(fitnessDesignTokens.spacing["0.5"])}]`,
    routineEditorHeaderActionButtonClassName: `min-h-[2.625rem] w-full rounded-[${fitnessDesignTokens.radii.md}] px-[${toArbitraryValue(fitnessDesignTokens.spacing["4"])}] py-[${toArbitraryValue(fitnessDesignTokens.spacing["2"])}] text-[0.92rem]`,
    routineEditorHeaderActionButtonDisabledClassName: `cursor-not-allowed opacity-55 hover:bg-[${withOpacity(fitnessDesignTokens.colors.surface["2"], "0.22")}] hover:text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.96")}]`,
    routineEditorModeSummaryClassName: `text-xs text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.96")}]`,
    routineEditorInlineTitleClassName: `text-[11px] font-semibold uppercase tracking-[0.16em] text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.96")}]`,
    routineEditorInlineDescriptionClassName: `text-xs text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.96")}]`,
    routineEditorInlineBadgeTextClassName: `text-[11px] font-medium text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.96")}]`,
    routineEditorOrderLabelClassName: `text-[11px] font-semibold uppercase tracking-[0.08em] text-[${withOpacity(fitnessDesignTokens.colors.text.muted, "0.96")}]`,
    routineEditorStatusTextClassName: `text-[${withOpacity(fitnessDesignTokens.colors.text.secondary, "0.74")}]`,
    routineEditorAutosaveErrorTextClassName: `text-xs text-[${withOpacity(fitnessDesignTokens.colors.status.danger, "0.94")}]`,
    routineEditorReorderItemClassName: `rounded-[${fitnessDesignTokens.radii.xl}] transition-all`,
    routineEditorHandleGlyphClassName: `text-base leading-none tracking-[-0.08em]`,
  },
} as const;
