export const appTokens = {
  panelBase: "relative isolate overflow-hidden rounded-[var(--radius-lg)] border border-[rgb(var(--border-strong)/0.18)] bg-[rgb(var(--surface-1-rgb)/0.88)] p-4 shadow-[var(--glass-shadow-base)] backdrop-blur-[10px]",
  panelMuted: "rounded-[var(--radius-md)] border border-[rgb(var(--border-strong)/0.14)] bg-[rgb(var(--surface-2)/0.72)] p-4",
  rowBase: "rounded-[var(--radius-md)] border border-[rgb(var(--border-strong)/0.18)] bg-[rgb(var(--surface-2)/0.84)] px-3.5 py-3",
  rowInteractive: "transition-[transform,filter] duration-75 ease-out active:scale-[0.992] active:brightness-[1.02]",
  rowAccent: "border-[rgb(var(--accent)/0.34)] bg-[rgb(var(--accent)/0.1)]",
  rowDefault: "border-[rgb(var(--border-strong)/0.18)] bg-[rgb(var(--surface-2)/0.84)] hover:border-[rgb(var(--border-strong)/0.28)] hover:bg-[rgb(var(--surface-3-rgb)/0.94)]",
  accentText: "text-[rgb(var(--accent))]",
  mutedText: "text-[rgb(var(--text-secondary)/0.96)]",
  metaText: "text-[rgb(var(--text-muted)/0.96)]",
  dividerBorder: "border-[rgb(var(--border-strong)/0.14)]",
  listDivider: "divide-y divide-[rgb(var(--border-strong)/0.12)]",
  stickyBar: "rounded-[var(--radius-lg)] border border-[rgb(var(--border-strong)/0.16)] bg-[rgb(var(--surface-1-rgb)/0.94)] px-2 py-2 shadow-[var(--glass-shadow-raised)] backdrop-blur-[10px]",
  badgeBase: "inline-flex items-center justify-center shrink-0 whitespace-nowrap leading-none rounded-full border px-2.5 py-1 text-[11px] font-semibold uppercase tracking-[0.14em]",
  todayBadge: "border-[rgb(var(--accent)/0.36)] bg-[rgb(var(--accent)/0.14)] text-[rgb(var(--text-primary))]",
  defaultBadge: "border-[rgb(var(--border-strong)/0.18)] bg-[rgb(var(--surface-3-rgb)/0.92)] text-[rgb(var(--text-primary)/0.9)]",
  successBadge: "border-[rgb(var(--success-rgb)/0.34)] bg-[rgb(var(--success-rgb)/0.14)] text-[rgb(var(--text-primary))]",
  warningBadge: "border-[rgb(var(--warning-rgb)/0.34)] bg-[rgb(var(--warning-rgb)/0.14)] text-[rgb(255_242_220)]",
  destructiveBadge: "border-[rgb(var(--danger-rgb)/0.34)] bg-[rgb(var(--danger-rgb)/0.12)] text-[rgb(255_228_233)]",
} as const;
