export const appTokens = {
  panelBase: "rounded-[1.5rem] border border-border/50 bg-[rgb(var(--surface-2-soft)/0.74)] p-4 shadow-[0_8px_20px_rgba(0,0,0,0.16)]",
  panelMuted: "rounded-xl border border-border/70 bg-surface/65 p-4",
  rowBase: "rounded-[1.25rem] border border-border/45 bg-[rgb(var(--surface-2-soft)/0.68)] px-3.5 py-3",
  rowInteractive: "transition duration-150 active:scale-[0.99]",
  rowAccent: "border-white/30 bg-white/[0.03]",
  rowDefault: "border-border/45 bg-[rgb(var(--surface-2-soft)/0.68)] hover:border-border/70 hover:bg-[rgb(var(--surface-2-soft)/0.82)]",
  accentText: "text-emerald-300",
  mutedText: "text-[rgb(var(--text)/0.66)]",
  metaText: "text-[rgb(var(--text)/0.54)]",
  dividerBorder: "border-white/15",
  listDivider: "divide-y divide-white/12",
  stickyBar: "rounded-[1.5rem] border border-white/12 bg-[rgb(var(--surface-rgb)/0.965)] px-2.5 py-2.5 shadow-[0_8px_22px_rgba(0,0,0,0.2)] backdrop-blur-md",
  todayBadge: "inline-flex items-center justify-center shrink-0 whitespace-nowrap leading-none rounded-full border border-white/70 bg-white/5 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-white shadow-[0_0_8px_rgba(255,255,255,0.15)]",
  defaultBadge: "inline-flex items-center justify-center shrink-0 whitespace-nowrap leading-none rounded-full border border-white/25 bg-white/10 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-white/90",
} as const;
