insert into public.exercises (name, user_id, is_global, primary_muscle, equipment)
values
  ('Barbell Bench Press', null, true, 'Chest', 'Barbell'),
  ('Incline Barbell Bench Press', null, true, 'Chest', 'Barbell'),
  ('Decline Barbell Bench Press', null, true, 'Chest', 'Barbell'),
  ('Close-Grip Bench Press', null, true, 'Chest', 'Barbell'),
  ('Paused Barbell Bench Press', null, true, 'Chest', 'Barbell'),
  ('Tempo Barbell Bench Press', null, true, 'Chest', 'Barbell'),
  ('Smith Machine Bench Press', null, true, 'Chest', 'Smith Machine'),
  ('Dumbbell Bench Press', null, true, 'Chest', 'Dumbbell'),
  ('Incline Dumbbell Bench Press', null, true, 'Chest', 'Dumbbell'),
  ('Decline Dumbbell Bench Press', null, true, 'Chest', 'Dumbbell'),
  ('Single-Arm Dumbbell Bench Press', null, true, 'Chest', 'Dumbbell'),
  ('Dumbbell Fly', null, true, 'Chest', 'Dumbbell'),
  ('Incline Dumbbell Fly', null, true, 'Chest', 'Dumbbell'),
  ('Cable Fly', null, true, 'Chest', 'Cable'),
  ('High-to-Low Cable Fly', null, true, 'Chest', 'Cable'),
  ('Low-to-High Cable Fly', null, true, 'Chest', 'Cable'),
  ('Pec Deck', null, true, 'Chest', 'Machine'),
  ('Push-Up', null, true, 'Chest', 'Bodyweight'),
  ('Weighted Push-Up', null, true, 'Chest', 'Bodyweight'),
  ('Deficit Push-Up', null, true, 'Chest', 'Bodyweight'),
  ('Dips (Chest)', null, true, 'Chest', 'Bodyweight'),

  ('Deadlift', null, true, 'Back', 'Barbell'),
  ('Paused Deadlift', null, true, 'Back', 'Barbell'),
  ('Tempo Deadlift', null, true, 'Back', 'Barbell'),
  ('Romanian Deadlift', null, true, 'Back', 'Barbell'),
  ('Stiff-Leg Deadlift', null, true, 'Back', 'Barbell'),
  ('Single-Leg Romanian Deadlift', null, true, 'Back', 'Dumbbell'),
  ('Rack Pull', null, true, 'Back', 'Barbell'),
  ('Snatch-Grip Deadlift', null, true, 'Back', 'Barbell'),
  ('Pull-Up', null, true, 'Back', 'Bodyweight'),
  ('Weighted Pull-Up', null, true, 'Back', 'Bodyweight'),
  ('Neutral-Grip Pull-Up', null, true, 'Back', 'Bodyweight'),
  ('Chin-Up', null, true, 'Back', 'Bodyweight'),
  ('Lat Pulldown', null, true, 'Back', 'Cable'),
  ('Wide-Grip Lat Pulldown', null, true, 'Back', 'Cable'),
  ('Close-Grip Lat Pulldown', null, true, 'Back', 'Cable'),
  ('Single-Arm Lat Pulldown', null, true, 'Back', 'Cable'),
  ('Seated Cable Row', null, true, 'Back', 'Cable'),
  ('Single-Arm Cable Row', null, true, 'Back', 'Cable'),
  ('Barbell Row', null, true, 'Back', 'Barbell'),
  ('Pendlay Row', null, true, 'Back', 'Barbell'),
  ('Yates Row', null, true, 'Back', 'Barbell'),
  ('Dumbbell Row', null, true, 'Back', 'Dumbbell'),
  ('Single-Arm Dumbbell Row', null, true, 'Back', 'Dumbbell'),
  ('Chest-Supported Row', null, true, 'Back', 'Machine'),
  ('T-Bar Row', null, true, 'Back', 'Machine'),
  ('Machine Row', null, true, 'Back', 'Machine'),
  ('Straight-Arm Pulldown', null, true, 'Back', 'Cable'),
  ('Face Pull', null, true, 'Shoulders', 'Cable'),
  ('Back Extension', null, true, 'Back', 'Bodyweight'),
  ('Reverse Hyperextension', null, true, 'Back', 'Machine'),

  ('Overhead Press', null, true, 'Shoulders', 'Barbell'),
  ('Push Press', null, true, 'Shoulders', 'Barbell'),
  ('Seated Barbell Overhead Press', null, true, 'Shoulders', 'Barbell'),
  ('Seated Dumbbell Shoulder Press', null, true, 'Shoulders', 'Dumbbell'),
  ('Arnold Press', null, true, 'Shoulders', 'Dumbbell'),
  ('Machine Shoulder Press', null, true, 'Shoulders', 'Machine'),
  ('Smith Machine Shoulder Press', null, true, 'Shoulders', 'Smith Machine'),
  ('Lateral Raise', null, true, 'Shoulders', 'Dumbbell'),
  ('Cable Lateral Raise', null, true, 'Shoulders', 'Cable'),
  ('Leaning Cable Lateral Raise', null, true, 'Shoulders', 'Cable'),
  ('Front Raise', null, true, 'Shoulders', 'Dumbbell'),
  ('Plate Front Raise', null, true, 'Shoulders', 'Plate'),
  ('Rear Delt Fly', null, true, 'Shoulders', 'Dumbbell'),
  ('Reverse Pec Deck', null, true, 'Shoulders', 'Machine'),
  ('Cable Rear Delt Fly', null, true, 'Shoulders', 'Cable'),
  ('Upright Row', null, true, 'Shoulders', 'Barbell'),

  ('Back Squat', null, true, 'Legs', 'Barbell'),
  ('High-Bar Back Squat', null, true, 'Legs', 'Barbell'),
  ('Low-Bar Back Squat', null, true, 'Legs', 'Barbell'),
  ('Paused Back Squat', null, true, 'Legs', 'Barbell'),
  ('Tempo Back Squat', null, true, 'Legs', 'Barbell'),
  ('Front Squat', null, true, 'Legs', 'Barbell'),
  ('Paused Front Squat', null, true, 'Legs', 'Barbell'),
  ('Goblet Squat', null, true, 'Legs', 'Dumbbell'),
  ('Hack Squat', null, true, 'Legs', 'Machine'),
  ('Smith Machine Squat', null, true, 'Legs', 'Smith Machine'),
  ('Leg Press', null, true, 'Legs', 'Machine'),
  ('Single-Leg Press', null, true, 'Legs', 'Machine'),
  ('Bulgarian Split Squat', null, true, 'Legs', 'Dumbbell'),
  ('Walking Lunge', null, true, 'Legs', 'Dumbbell'),
  ('Reverse Lunge', null, true, 'Legs', 'Dumbbell'),
  ('Step-Up', null, true, 'Legs', 'Dumbbell'),
  ('Leg Extension', null, true, 'Legs', 'Machine'),
  ('Seated Leg Curl', null, true, 'Legs', 'Machine'),
  ('Lying Leg Curl', null, true, 'Legs', 'Machine'),
  ('Nordic Curl', null, true, 'Legs', 'Bodyweight'),
  ('Glute Bridge', null, true, 'Glutes', 'Barbell'),
  ('Hip Thrust', null, true, 'Glutes', 'Barbell'),
  ('Single-Leg Hip Thrust', null, true, 'Glutes', 'Bodyweight'),
  ('Cable Kickback', null, true, 'Glutes', 'Cable'),
  ('Abductor Machine', null, true, 'Glutes', 'Machine'),
  ('Adductor Machine', null, true, 'Legs', 'Machine'),
  ('Calf Raise (Standing)', null, true, 'Legs', 'Machine'),
  ('Calf Raise (Seated)', null, true, 'Legs', 'Machine'),
  ('Donkey Calf Raise', null, true, 'Legs', 'Machine'),

  ('Barbell Curl', null, true, 'Arms', 'Barbell'),
  ('EZ-Bar Curl', null, true, 'Arms', 'Barbell'),
  ('Cable Curl', null, true, 'Arms', 'Cable'),
  ('Dumbbell Curl', null, true, 'Arms', 'Dumbbell'),
  ('Alternating Dumbbell Curl', null, true, 'Arms', 'Dumbbell'),
  ('Hammer Curl', null, true, 'Arms', 'Dumbbell'),
  ('Cross-Body Hammer Curl', null, true, 'Arms', 'Dumbbell'),
  ('Incline Dumbbell Curl', null, true, 'Arms', 'Dumbbell'),
  ('Concentration Curl', null, true, 'Arms', 'Dumbbell'),
  ('Preacher Curl', null, true, 'Arms', 'Machine'),
  ('Machine Biceps Curl', null, true, 'Arms', 'Machine'),
  ('Triceps Pushdown', null, true, 'Arms', 'Cable'),
  ('Rope Pushdown', null, true, 'Arms', 'Cable'),
  ('Reverse-Grip Pushdown', null, true, 'Arms', 'Cable'),
  ('Overhead Triceps Extension', null, true, 'Arms', 'Cable'),
  ('Dumbbell Overhead Triceps Extension', null, true, 'Arms', 'Dumbbell'),
  ('Skullcrusher', null, true, 'Arms', 'Barbell'),
  ('Close-Grip Push-Up', null, true, 'Arms', 'Bodyweight'),
  ('Dips (Triceps)', null, true, 'Arms', 'Bodyweight'),

  ('Plank', null, true, 'Core', 'Bodyweight'),
  ('Weighted Plank', null, true, 'Core', 'Bodyweight'),
  ('Side Plank', null, true, 'Core', 'Bodyweight'),
  ('Hanging Leg Raise', null, true, 'Core', 'Bodyweight'),
  ('Lying Leg Raise', null, true, 'Core', 'Bodyweight'),
  ('Cable Crunch', null, true, 'Core', 'Cable'),
  ('Machine Crunch', null, true, 'Core', 'Machine'),
  ('Ab Wheel Rollout', null, true, 'Core', 'Bodyweight'),
  ('Russian Twist', null, true, 'Core', 'Bodyweight'),
  ('Dead Bug', null, true, 'Core', 'Bodyweight'),
  ('Pallof Press', null, true, 'Core', 'Cable'),
  ('Hollow Body Hold', null, true, 'Core', 'Bodyweight'),

  ('Treadmill Run', null, true, 'Cardio', 'Cardio Machine'),
  ('Incline Walk', null, true, 'Cardio', 'Cardio Machine'),
  ('Stationary Bike', null, true, 'Cardio', 'Cardio Machine'),
  ('Rowing Machine', null, true, 'Cardio', 'Cardio Machine'),
  ('Stair Climber', null, true, 'Cardio', 'Cardio Machine'),
  ('Jump Rope', null, true, 'Cardio', 'Bodyweight'),
  ('Air Bike Sprint', null, true, 'Cardio', 'Cardio Machine'),
  ('Sled Push', null, true, 'Cardio', 'Sled')
on conflict (name) where user_id is null do nothing;
